
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,fa="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.Dg&&"string"==typeof process.Dg.node,k=g.ENVIRONMENT_IS_PTHREAD||!1,_scriptDir="undefined"!=typeof document&&document.currentScript?document.currentScript.src:void 0;fa&&(_scriptDir=self.location.href);var ka="";
function la(a){return g.locateFile?g.locateFile(a,ka):ka+a}var ma,na;if(ea||fa)fa?ka=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),na=a=>{document.title=a};var oa=g.print||console.log.bind(console),l=g.printErr||console.warn.bind(console);
Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var pa;g.wasmBinary&&(pa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&p("no native wasm support detected");var qa,ra,sa=!1,ta="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ta)return ta.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function va(a,b){return a?ua(q,a,b):""}function wa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var m=a.charCodeAt(++f);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function r(a,b,c){return wa(a,q,b,c)}function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var ya,t,q,za,Aa,v,w,y,B;k&&(ya=g.buffer);var Ba=g.INITIAL_MEMORY||33554432;
if(k)qa=g.wasmMemory,ya=g.buffer;else if(g.wasmMemory)qa=g.wasmMemory;else if(qa=new WebAssembly.Memory({initial:Ba/65536,maximum:Ba/65536,shared:!0}),!(qa.buffer instanceof SharedArrayBuffer))throw l("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),ha&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");qa&&(ya=qa.buffer);Ba=ya.byteLength;var Ca=ya;ya=Ca;g.HEAP8=t=new Int8Array(Ca);g.HEAP16=za=new Int16Array(Ca);g.HEAP32=v=new Int32Array(Ca);g.HEAPU8=q=new Uint8Array(Ca);g.HEAPU16=Aa=new Uint16Array(Ca);g.HEAPU32=w=new Uint32Array(Ca);g.HEAPF32=y=new Float32Array(Ca);g.HEAPF64=B=new Float64Array(Ca);var Da,Ea=[],Fa=[],Ga=[],Ha=[],Ia=[];
function Ja(){k||(g.noFSInit||Ka||(Ka=!0,La(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Ma("stdin",g.stdin):Na("/dev/tty","/dev/stdin"),g.stdout?Ma("stdout",null,g.stdout):Na("/dev/tty","/dev/stdout"),g.stderr?Ma("stderr",null,g.stderr):Na("/dev/tty1","/dev/stderr"),Oa("/dev/stdin",0),Oa("/dev/stdout",1),Oa("/dev/stderr",1)),Pa=!1,Qa(Fa))}function Ra(){var a=g.preRun.shift();Ea.unshift(a)}var Sa=0,Ta=null,Ua=null;
function p(a){if(k)postMessage({cmd:"onAbort",arg:a});else if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";l(a);sa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Va(){return Wa.startsWith("data:application/octet-stream;base64,")}var Wa;Wa="chip8pp.wasm";Va()||(Wa=la(Wa));function Xa(){var a=Wa;try{if(a==Wa&&pa)return new Uint8Array(pa);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function Ya(){return pa||!ea&&!fa||"function"!=typeof fetch?Promise.resolve().then(function(){return Xa()}):fetch(Wa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Wa+"'";return a.arrayBuffer()}).catch(function(){return Xa()})}
var C,Za,cb={60188:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,60335:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,60569:a=>{"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;a?b.capture={}:b.audio={};b.ke||("undefined"!==typeof AudioContext?b.ke=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ke=new webkitAudioContext),b.ke&&
$a(b.ke));return void 0===b.ke?-1:0},61062:()=>g.SDL2.ke.sampleRate,61130:(a,b,c,d)=>{function e(){}function f(m){void 0!==h.capture.Pe&&(clearTimeout(h.capture.Pe),h.capture.Pe=void 0);h.capture.Xe=h.ke.createMediaStreamSource(m);h.capture.ne=h.ke.createScriptProcessor(b,a,1);h.capture.ne.onaudioprocess=function(n){void 0!==h&&void 0!==h.capture&&(n.outputBuffer.getChannelData(0).fill(0),h.capture.ef=n.inputBuffer,ab(c,[d]))};h.capture.Xe.connect(h.capture.ne);h.capture.ne.connect(h.ke.destination);
h.capture.stream=m}var h=g.SDL2;h.capture.bf=h.ke.createBuffer(a,b,h.ke.sampleRate);h.capture.bf.getChannelData(0).fill(0);h.capture.Pe=setTimeout(function(){h.capture.ef=h.capture.bf;ab(c,[d])},b/h.ke.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},62782:(a,b,c,d)=>{var e=g.SDL2;e.audio.ne=
e.ke.createScriptProcessor(b,0,a);e.audio.ne.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.vf=f.outputBuffer,ab(c,[d]))};e.audio.ne.connect(e.ke.destination)},63192:(a,b)=>{for(var c=g.SDL2,d=c.capture.ef.numberOfChannels,e=0;e<d;++e){var f=c.capture.ef.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var h=0;h<b;++h)bb(a+4*h,f[h]);else for(h=0;h<b;++h)bb(a+4*(h*d+e),
f[h])}},63797:(a,b)=>{for(var c=g.SDL2,d=c.audio.vf.numberOfChannels,e=0;e<d;++e){var f=c.audio.vf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)f[h]=y[a+(h*d+e<<2)>>2]}},64277:a=>{var b=g.SDL2;if(a){void 0!==b.capture.Pe&&clearTimeout(b.capture.Pe);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=
void 0}void 0!==b.capture.ne&&(b.capture.ne.onaudioprocess=function(){},b.capture.ne.disconnect(),b.capture.ne=void 0);void 0!==b.capture.Xe&&(b.capture.Xe.disconnect(),b.capture.Xe=void 0);void 0!==b.capture.bf&&(b.capture.bf=void 0);b.capture=void 0}else void 0!=b.audio.ne&&(b.audio.ne.disconnect(),b.audio.ne=void 0),b.audio=void 0;void 0!==b.ke&&void 0===b.audio&&void 0===b.capture&&(b.ke.close(),b.ke=void 0)},65449:(a,b,c)=>{g.SDL2||(g.SDL2={});var d=g.SDL2;d.Yf!==g.canvas&&(d.ue=g.createContext(g.canvas,
!1,!0),d.Yf=g.canvas);if(d.w!==a||d.hg!==b||d.kg!==d.ue)d.image=d.ue.createImageData(a,b),d.w=a,d.hg=b,d.kg=d.ue;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=v[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.ag!==a&&(d.$f=new Int32Array(a.buffer),d.bg=new Uint8Array(a.buffer),d.ag=a),a=d.$f,c=a.length,a.set(v.subarray(b,b+c)),a=d.bg,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,
b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ue.putImageData(d.image,0,0)},66918:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var h=f.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var u=v[e];b[m]=u&255;b[m+1]=u>>8&255;b[m+2]=u>>16&255;b[m+3]=u>>24&255;e++;m+=
4}else b=new Int32Array(b.buffer),n=b.length,b.set(v.subarray(e,e+n));h.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);r(c,d,c.length+1);return d},67907:a=>{g.canvas&&(g.canvas.style.cursor=va(a))},67990:()=>{g.canvas&&(g.canvas.style.cursor="none")},68059:()=>window.innerWidth,68089:()=>window.innerHeight};function db(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function eb(a){(a=E.Ae[a])||p();E.Pf(a)}function fb(a){var b=E.gg();if(!b)return 6;E.Oe.push(b);E.Ae[a.ze]=b;b.ze=a.ze;var c={cmd:"run",start_routine:a.yg,arg:a.rf,pthread_ptr:a.ze};b.Ne=()=>{c.time=performance.now();b.postMessage(c,a.Ag)};b.loaded&&(b.Ne(),delete b.Ne);return 0}
var gb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},hb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ib=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},jb=a=>
{if("/"===a)return"/";a=hb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function kb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>p("randomDevice")}
function lb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var mb=[];function nb(a,b){mb[a]={input:[],me:[],Ke:b};ob(a,pb)}
var pb={open:function(a){var b=mb[a.node.af];if(!b)throw new F(43);a.je=b;a.seekable=!1},close:function(a){a.je.Ke.Te(a.je)},Te:function(a){a.je.Ke.Te(a.je)},read:function(a,b,c,d){if(!a.je||!a.je.Ke.Af)throw new F(60);for(var e=0,f=0;f<d;f++){try{var h=a.je.Ke.Af(a.je)}catch(m){throw new F(29);}if(void 0===h&&0===e)throw new F(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.je||!a.je.Ke.jf)throw new F(60);try{for(var e=0;e<d;e++)a.je.Ke.jf(a.je,
b[c+e])}catch(f){throw new F(29);}d&&(a.node.timestamp=Date.now());return e}},qb={Af:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;var c=Array(xa(b)+1);b=wa(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},jf:function(a,b){null===b||10===b?(oa(ua(a.me,0)),a.me=[]):0!=b&&a.me.push(b)},Te:function(a){a.me&&
0<a.me.length&&(oa(ua(a.me,0)),a.me=[])}},rb={jf:function(a,b){null===b||10===b?(l(ua(a.me,0)),a.me=[]):0!=b&&a.me.push(b)},Te:function(a){a.me&&0<a.me.length&&(l(ua(a.me,0)),a.me=[])}},G={ve:null,ye:function(){return G.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);G.ve||(G.ve={dir:{node:{De:G.ge.De,we:G.ge.we,Le:G.ge.Le,Ye:G.ge.Ye,Of:G.ge.Of,Wf:G.ge.Wf,Qf:G.ge.Qf,Nf:G.ge.Nf,cf:G.ge.cf},stream:{He:G.he.He}},file:{node:{De:G.ge.De,
we:G.ge.we},stream:{He:G.he.He,read:G.he.read,write:G.he.write,pf:G.he.pf,Gf:G.he.Gf,If:G.he.If}},link:{node:{De:G.ge.De,we:G.ge.we,Me:G.ge.Me},stream:{}},tf:{node:{De:G.ge.De,we:G.ge.we},stream:sb}});c=tb(a,b,c,d);16384===(c.mode&61440)?(c.ge=G.ve.dir.node,c.he=G.ve.dir.stream,c.fe={}):32768===(c.mode&61440)?(c.ge=G.ve.file.node,c.he=G.ve.file.stream,c.ie=0,c.fe=null):40960===(c.mode&61440)?(c.ge=G.ve.link.node,c.he=G.ve.link.stream):8192===(c.mode&61440)&&(c.ge=G.ve.tf.node,c.he=G.ve.tf.stream);
c.timestamp=Date.now();a&&(a.fe[b]=c,a.timestamp=c.timestamp);return c},Og:function(a){return a.fe?a.fe.subarray?a.fe.subarray(0,a.ie):new Uint8Array(a.fe):new Uint8Array(0)},xf:function(a,b){var c=a.fe?a.fe.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.fe,a.fe=new Uint8Array(b),0<a.ie&&a.fe.set(c.subarray(0,a.ie),0))},vg:function(a,b){if(a.ie!=b)if(0==b)a.fe=null,a.ie=0;else{var c=a.fe;a.fe=new Uint8Array(b);c&&a.fe.set(c.subarray(0,Math.min(b,a.ie)));a.ie=
b}},ge:{De:function(a){var b={};b.Lg=8192===(a.mode&61440)?a.id:1;b.Qg=a.id;b.mode=a.mode;b.Vg=1;b.uid=0;b.Pg=0;b.af=a.af;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ie:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Gg=new Date(a.timestamp);b.Tg=new Date(a.timestamp);b.Kg=new Date(a.timestamp);b.Xf=4096;b.Hg=Math.ceil(b.size/b.Xf);return b},we:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&G.vg(a,b.size)},
Le:function(){throw ub[44];},Ye:function(a,b,c,d){return G.createNode(a,b,c,d)},Of:function(a,b,c){if(16384===(a.mode&61440)){try{var d=vb(b,c)}catch(f){}if(d)for(var e in d.fe)throw new F(55);}delete a.parent.fe[a.name];a.parent.timestamp=Date.now();a.name=c;b.fe[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Wf:function(a,b){delete a.fe[b];a.timestamp=Date.now()},Qf:function(a,b){var c=vb(a,b),d;for(d in c.fe)throw new F(55);delete a.fe[b];a.timestamp=Date.now()},Nf:function(a){var b=[".",".."],
c;for(c in a.fe)a.fe.hasOwnProperty(c)&&b.push(c);return b},cf:function(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},Me:function(a){if(40960!==(a.mode&61440))throw new F(28);return a.link}},he:{read:function(a,b,c,d,e){var f=a.node.fe;if(e>=a.node.ie)return 0;a=Math.min(a.node.ie-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.fe||a.fe.subarray)){if(f)return a.fe=
b.subarray(c,c+d),a.ie=d;if(0===a.ie&&0===e)return a.fe=b.slice(c,c+d),a.ie=d;if(e+d<=a.ie)return a.fe.set(b.subarray(c,c+d),e),d}G.xf(a,e+d);if(a.fe.subarray&&b.subarray)a.fe.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.fe[e+f]=b[c+f];a.ie=Math.max(a.ie,e+d);return d},He:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ie);if(0>b)throw new F(28);return b},pf:function(a,b,c){G.xf(a.node,b+c);a.node.ie=Math.max(a.node.ie,b+c)},Gf:function(a,b,c,d,e){if(32768!==
(a.node.mode&61440))throw new F(43);a=a.node.fe;if(e&2||a.buffer!==ya){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;p();b=void 0;if(!b)throw new F(48);t.set(a,b)}else c=!1,b=a.byteOffset;return{Ie:b,Fg:c}},If:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(43);if(e&2)return 0;G.he.write(a,b,0,d,c,!1);return 0}}},wb=null,xb={},yb=[],zb=1,Ab=null,Pa=!0,F=null,ub={},Cb=(a,b={})=>{a=lb("/",a);if(!a)return{path:"",node:null};b=Object.assign({zf:!0,
kf:0},b);if(8<b.kf)throw new F(32);a=gb(a.split("/").filter(h=>!!h),!1);for(var c=wb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=vb(c,a[e]);d=hb(d+"/"+a[e]);c.Ze&&(!f||f&&b.zf)&&(c=c.Ze.root);if(!f||b.yf)for(f=0;40960===(c.mode&61440);)if(c=Bb(d),d=lb(ib(d),c),c=Cb(d,{kf:b.kf+1}).node,40<f++)throw new F(32);}return{path:d,node:c}},Db=a=>{for(var b;;){if(a===a.parent)return a=a.ye.Hf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Eb=(a,b)=>{for(var c=
0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ab.length},vb=(a,b)=>{var c;if(c=(c=Fb(a,"x"))?c:a.ge.Le?0:2)throw new F(c,a);for(c=Ab[Eb(a.id,b)];c;c=c.sg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ge.Le(a,b)},tb=(a,b,c,d)=>{a=new Gb(a,b,c,d);b=Eb(a.parent.id,a.name);a.sg=Ab[b];return Ab[b]=a},Hb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Ib=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Fb=(a,b)=>{if(Pa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&
!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Jb=(a,b)=>{try{return vb(a,b),20}catch(c){}return Fb(a,"wx")},Kb=(a=0)=>{for(;4096>=a;a++)if(!yb[a])return a;throw new F(33);},Mb=(a,b)=>{Lb||(Lb=function(){this.oe={}},Lb.prototype={},Object.defineProperties(Lb.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.oe.flags},set:function(c){this.oe.flags=c}},position:{get:function(){return this.oe.position},set:function(c){this.oe.position=
c}}}));a=Object.assign(new Lb,a);b=Kb(b);a.Ce=b;return yb[b]=a},sb={open:a=>{a.he=xb[a.node.af].he;a.he.open&&a.he.open(a)},He:()=>{throw new F(70);}},ob=(a,b)=>{xb[a]={he:b}},Nb=(a,b)=>{var c="/"===b,d=!b;if(c&&wb)throw new F(10);if(!c&&!d){var e=Cb(b,{zf:!1});b=e.path;e=e.node;if(e.Ze)throw new F(10);if(16384!==(e.mode&61440))throw new F(54);}b={type:a,Xg:{},Hf:b,rg:[]};a=a.ye(b);a.ye=b;b.root=a;c?wb=a:e&&(e.Ze=b,e.ye&&e.ye.rg.push(b))},H=(a,b,c)=>{var d=Cb(a,{parent:!0}).node;a=jb(a);if(!a||"."===
a||".."===a)throw new F(28);var e=Jb(d,a);if(e)throw new F(e);if(!d.ge.Ye)throw new F(63);return d.ge.Ye(d,a,b,c)},Ob=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);H(a,b|8192,c)},Na=(a,b)=>{if(!lb(a))throw new F(44);var c=Cb(b,{parent:!0}).node;if(!c)throw new F(44);b=jb(b);var d=Jb(c,b);if(d)throw new F(d);if(!c.ge.cf)throw new F(63);c.ge.cf(c,b,a)},Bb=a=>{a=Cb(a).node;if(!a)throw new F(44);if(!a.ge.Me)throw new F(28);return lb(Db(a.parent),a.ge.Me(a))},Oa=(a,b,c)=>{if(""===a)throw new F(44);if("string"==
typeof b){var d=Hb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=hb(a);try{e=Cb(a,{yf:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new F(20);}else e=H(a,c,0),d=!0;if(!e)throw new F(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new F(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Ib(b)||b&512)?31:Fb(e,Ib(b)):
44))throw new F(c);if(b&512&&!d){c=e;c="string"==typeof c?Cb(c,{yf:!0}).node:c;if(!c.ge.we)throw new F(63);if(16384===(c.mode&61440))throw new F(31);if(32768!==(c.mode&61440))throw new F(28);if(d=Fb(c,"w"))throw new F(d);c.ge.we(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Mb({node:e,path:Db(e),flags:b,seekable:!0,position:0,he:e.he,Bg:[],error:!1});e.he.open&&e.he.open(e);!g.logReadFiles||b&1||(Pb||(Pb={}),a in Pb||(Pb[a]=1));return e},Qb=(a,b,c)=>{if(null===a.Ce)throw new F(8);if(!a.seekable||
!a.he.He)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.he.He(a,b,c);a.Bg=[]},La=()=>{F||(F=function(a,b){this.node=b;this.wg=function(c){this.Ge=c};this.wg(a);this.message="FS error"},F.prototype=Error(),F.prototype.constructor=F,[44].forEach(a=>{ub[a]=new F(a);ub[a].stack="<generic error, no stack>"}))},Ka,Rb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ma=(a,b,c)=>{a=hb("/dev/"+a);var d=Rb(!!b,!!c);Sb||(Sb=64);var e=Sb++<<8|0;ob(e,{open:f=>{f.seekable=!1},close:()=>{c&&c.buffer&&
c.buffer.length&&c(10)},read:(f,h,m,n)=>{for(var u=0,x=0;x<n;x++){try{var z=b()}catch(A){throw new F(29);}if(void 0===z&&0===u)throw new F(6);if(null===z||void 0===z)break;u++;h[m+x]=z}u&&(f.node.timestamp=Date.now());return u},write:(f,h,m,n)=>{for(var u=0;u<n;u++)try{c(h[m+u])}catch(x){throw new F(29);}n&&(f.node.timestamp=Date.now());return u}});Ob(a,d,e)},Sb,Tb={},Lb,Pb,Ub=void 0;function Vb(){Ub+=4;return v[Ub-4>>2]}function Wb(a){a=yb[a];if(!a)throw new F(8);return a}
function Xb(a){if(k)return I(1,1,a);if(!noExitRuntime){E.zg();if(g.onExit)g.onExit(a);sa=!0}da(a,new db(a))}function Yb(a,b){if(!b&&k)throw Zb(a),"unwind";Xb(a)}function $b(a){a instanceof db||"unwind"==a||da(1,a)}
var E={Be:[],Oe:[],Tf:[],Ae:{},hf:function(){k?E.ng():E.mg()},mg:function(){for(var a=4;a--;)E.qf()},ng:function(){E.receiveObjectTransfer=E.ug;E.threadInitTLS=E.Sf;E.setExitStatus=E.Rf;noExitRuntime=!1},Rf:function(){},zg:function(){for(var a of Object.values(E.Ae))E.Pf(a);for(a of E.Be)a.terminate();E.Be=[]},Pf:function(a){var b=a.ze;delete E.Ae[b];E.Be.push(a);E.Oe.splice(E.Oe.indexOf(a),1);a.ze=0;ac(b)},ug:function(){},Sf:function(){E.Tf.forEach(a=>a())},Ef:function(a,b){a.onmessage=c=>{c=c.data;
var d=c.cmd;a.ze&&(E.wf=a.ze);if(c.targetThread&&c.targetThread!=bc()){var e=E.Ae[c.Yg];e?e.postMessage(c,c.transferList):l('Internal error! Worker sent a message "'+d+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===d)cc(c.queue);else if("spawnThread"===d)fb(c);else if("cleanupThread"===d)eb(c.thread);else if("killThread"===d)c=c.thread,d=E.Ae[c],delete E.Ae[c],d.terminate(),ac(c),E.Oe.splice(E.Oe.indexOf(d),1),d.ze=0;else if("cancelThread"===
d)E.Ae[c.thread].postMessage({cmd:"cancel"});else if("loaded"===d)a.loaded=!0,b&&b(a),a.Ne&&(a.Ne(),delete a.Ne);else if("print"===d)oa("Thread "+c.threadId+": "+c.text);else if("printErr"===d)l("Thread "+c.threadId+": "+c.text);else if("alert"===d)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===c.target)a.postMessage(c);else if("onAbort"===d){if(g.onAbort)g.onAbort(c.arg)}else d&&l("worker sent an unknown command "+d);E.wf=void 0};a.onerror=c=>{l("worker sent an error! "+c.filename+
":"+c.lineno+": "+c.message);throw c;};a.postMessage({cmd:"load",urlOrBlob:g.mainScriptUrlOrBlob||_scriptDir,wasmMemory:qa,wasmModule:ra})},qf:function(){var a=la("chip8pp.worker.js");E.Be.push(new Worker(a))},gg:function(){0==E.Be.length&&(E.qf(),E.Ef(E.Be[0]));return E.Be.pop()}};g.PThread=E;function dc(a,b,c){a.addEventListener(b,c,{once:!0})}
function $a(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&dc(d,c,()=>{"suspended"===a.state&&a.resume()})})})}function Qa(a){for(;0<a.length;)a.shift()(g)}function ec(a){var b=fc();a=a();gc(b);return a}var hc=[];function J(a){var b=hc[a];b||(a>=hc.length&&(hc.length=a+1),hc[a]=b=Da.get(a));return b}
function ab(a,b){if("vi".includes("j")){var c=g.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else J(a).apply(null,b)}g.establishStackSpace=function(){var a=bc(),b=v[a+44>>2];ic(b,b-v[a+48>>2]);gc(b)};function Zb(a){if(k)return I(2,0,a);try{Yb(a)}catch(b){$b(b)}}g.invokeEntryPoint=function(a,b){a=J(a)(b);noExitRuntime?E.Rf(a):jc(a)};
function bb(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":t[a>>0]=b;break;case "i8":t[a>>0]=b;break;case "i16":za[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":Za=[b>>>0,(C=b,1<=+Math.abs(C)?0<C?(Math.min(+Math.floor(C/4294967296),4294967295)|0)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];v[a>>2]=Za[0];v[a+4>>2]=Za[1];break;case "float":y[a>>2]=b;break;case "double":B[a>>3]=b;break;case "*":w[a>>2]=b;break;default:p("invalid type for setValue: "+c)}}
function kc(a){this.Ie=a-24;this.qg=function(b){w[this.Ie+4>>2]=b};this.Bf=function(b){w[this.Ie+8>>2]=b};this.Cf=function(){v[this.Ie>>2]=0};this.ff=function(){t[this.Ie+12>>0]=0};this.pg=function(){t[this.Ie+13>>0]=0};this.hf=function(b,c){this.oe();this.qg(b);this.Bf(c);this.Cf();this.ff();this.pg()};this.oe=function(){w[this.Ie+16>>2]=0}}var lc=0;function mc(a,b,c,d){return k?I(3,1,a,b,c,d):nc(a,b,c,d)}
function nc(a,b,c,d){if("undefined"==typeof SharedArrayBuffer)return l("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(k&&0===e.length)return mc(a,b,c,d);a={yg:c,ze:a,rf:d,Ag:e};return k?(a.Ig="spawnThread",postMessage(a,e),0):fb(a)}
function oc(a,b,c){if(k)return I(4,1,a,b,c);Ub=c;try{var d=Wb(a);switch(b){case 0:var e=Vb();return 0>e?-28:Mb(d,e).Ce;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Vb(),d.flags|=e,0;case 5:return e=Vb(),za[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return v[pc()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof Tb||!(f instanceof F))throw f;return-f.Ge}}
function qc(a,b,c){if(k)return I(5,1,a,b,c);Ub=c;try{var d=Wb(a);switch(b){case 21509:case 21505:return d.je?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.je?0:-59;case 21519:if(!d.je)return-59;var e=Vb();return v[e>>2]=0;case 21520:return d.je?-28:-59;case 21531:a=e=Vb();if(!d.he.og)throw new F(59);return d.he.og(d,b,a);case 21523:return d.je?0:-59;case 21524:return d.je?0:-59;default:return-28}}catch(f){if("undefined"==typeof Tb||!(f instanceof F))throw f;return-f.Ge}}
function rc(a,b,c,d){if(k)return I(6,1,a,b,c,d);Ub=d;try{b=va(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Wb(a).path;if(0==e.length)throw new F(44);b=hb(f+"/"+e)}var h=d?Vb():0;return Oa(b,c,h).Ce}catch(m){if("undefined"==typeof Tb||!(m instanceof F))throw m;return-m.Ge}}function cc(a){Atomics.store(v,a>>2,1);bc()&&sc(a);Atomics.compareExchange(v,a>>2,1,0)}g.executeNotifiedProxyingQueue=cc;
function tc(a,b){uc=a;vc=b;if(wc)if(xc||(xc=!0),0==a)yc=function(){var d=Math.max(0,zc+b-Ac())|0;setTimeout(Bc,d)};else if(1==a)yc=function(){Cc(Bc)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);fa?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}yc=function(){setImmediate(Bc)}}}var Ac;Ac=k?()=>performance.now()-g.__performance_now_clock_drift:()=>performance.now();
function Dc(a,b,c,d,e){!wc||p("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");wc=a;Ec=d;var f=Fc;xc=!1;Bc=function(){if(!sa)if(0<Gc.length){var h=Date.now(),m=Gc.shift();m.Ng(m.rf);if(Hc){var n=Hc,u=0==n%1?n-1:Math.floor(n);Hc=m.Jg?u:(8*n+(u+.5))/9}oa('main loop blocker "'+m.name+'" took '+(Date.now()-h)+" ms");g.setStatus&&(h=g.statusMessage||"Please wait...",
m=Hc,n=Ic.Mg,m?m<n?g.setStatus(h+" ("+(n-m)+"/"+n+")"):g.setStatus(h):g.setStatus(""));f<Fc||setTimeout(Bc,0)}else f<Fc||(Jc=Jc+1|0,1==uc&&1<vc&&0!=Jc%vc?yc():(0==uc&&(zc=Ac()),sa||g.preMainLoop&&!1===g.preMainLoop()||(Kc(a),g.postMainLoop&&g.postMainLoop()),f<Fc||("object"==typeof SDL&&SDL.audio&&SDL.audio.tg&&SDL.audio.tg(),yc())))};e||(b&&0<b?tc(0,1E3/b):tc(1,1),yc());if(c)throw"unwind";}function Kc(a){if(!sa)try{a()}catch(b){$b(b)}}function Lc(a){setTimeout(function(){Kc(a)},1E4)}
function Mc(a){Nc||(Nc={});Nc[a]||(Nc[a]=1,l(a))}var Nc,xc=!1,yc=null,Fc=0,wc=null,Ec=0,uc=0,vc=0,Jc=0,Gc=[],Ic={},zc,Bc,Hc,Oc=!1,Pc=!1,Qc=[];
function Rc(){function a(){Pc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Sc){Sc=!0;try{Tc=!0}catch(c){Tc=!1,l("warning: no blob constructor, cannot create blobs with mimetypes")}Uc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Tc?null:l("warning: no BlobBuilder");Vc="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Jf||"undefined"!=typeof Vc||(l("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Jf=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Jf&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(Tc)try{h=new Blob([c],{type:Wc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Wc(d)}))}catch(u){Mc("Blob constructor present but fails: "+
u+"; falling back to blob builder")}h||(h=new Uc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=Vc.createObjectURL(h),n=new Image;n.onload=()=>{n.complete||p("Image "+d+" could not be decoded");var u=document.createElement("canvas");u.width=n.width;u.height=n.height;u.getContext("2d").drawImage(n,0,0);Vc.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{oa("Image "+m+" could not be decoded");f&&f()};n.src=m}});g.preloadPlugins.push({canHandle:function(c){return!g.Wg&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,f){function h(){n||(n=!0,e&&e(c))}function m(){n||(n=!0,new Audio,f&&f())}var n=!1;if(Tc){try{var u=new Blob([c],{type:Wc(d)})}catch(z){return m()}u=Vc.createObjectURL(u);var x=new Audio;x.addEventListener("canplaythrough",()=>h(x),!1);x.onerror=function(){if(!n){l("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var z="",A=0,K=0,N=0;N<c.length;N++)for(A=A<<8|c[N],K+=8;6<=K;){var ia=A>>K-6&63;K-=6;z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[ia]}2==
K?(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(A&3)<<4],z+="=="):4==K&&(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(A&15)<<2],z+="=");x.src="data:audio/x-"+d.substr(-3)+";base64,"+z;h(x)}};x.src=u;Lc(function(){h(x)})}else return m()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!Pc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Xc(a,b,c,d){if(b&&g.ue&&a==g.canvas)return g.ue;var e;if(b){var f={antialias:!1,alpha:!1,Ff:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!=typeof Yc&&(e=Zc(a,f)))var m=L[e].qe}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof M||p("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.ue=m,b&&$c(e),g.Cg=b,Qc.forEach(function(n){n()}),Rc());return m}var ad=!1,bd=void 0,cd=void 0;
function dd(a,b){function c(){Oc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=ed,bd&&d.requestPointerLock(),Oc=!0,cd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=w[SDL.screen>>2]|8388608),fd(g.canvas),gd()):fd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),cd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=w[SDL.screen>>2]&
-8388609),fd(g.canvas),gd()):fd(d));if(g.onFullScreen)g.onFullScreen(Oc);if(g.onFullscreen)g.onFullscreen(Oc)}bd=a;cd=b;"undefined"==typeof bd&&(bd=!0);"undefined"==typeof cd&&(cd=!1);var d=g.canvas;ad||(ad=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function ed(){if(!Oc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var hd=0;function Cc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===hd)hd=b+1E3/60;else for(;b+2>=hd;)hd+=1E3/60;setTimeout(a,Math.max(hd-b,0))}}
function Wc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var jd=[];function gd(){var a=g.canvas;jd.forEach(function(b){b(a.width,a.height)})}
function fd(a,b,c){b&&c?(a.Eg=b,a.jg=c):(b=a.Eg,c=a.jg);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}cd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Sc,Tc,Uc,Vc,O=12288,kd=!1,ld=0,md=0,nd=0,P={alpha:!1,depth:!1,stencil:!1,antialias:!1},od={},pd;function qd(a){if(k)return I(7,1,a);if(12448==a)return O=12288,1;O=12300;return 0}
function rd(a,b,c,d,e){if(k)c=I(8,1,a,b,c,d,e);else if(62E3!=a)O=12296,c=0;else{if(b)for(;;){a=v[b>>2];if(12321==a)P.alpha=0<v[b+4>>2];else if(12325==a)P.depth=0<v[b+4>>2];else if(12326==a)P.stencil=0<v[b+4>>2];else if(12337==a)a=v[b+4>>2],P.antialias=0<a;else if(12338==a)a=v[b+4>>2],P.antialias=1==a;else if(12544==a)P.Rg=12547!=v[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(v[e>>2]=1),c&&0<d&&(v[c>>2]=62002),O=12288,c=1):(O=12300,c=0)}return c}
function sd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function td(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function ud(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var vd=1,wd=[],Q=[],xd=[],yd=[],zd=[],R=[],Ad=[],L={},S=[],Bd={},Cd=4;
function T(a){Dd||(Dd=a)}function Ed(a){for(var b=vd++,c=a.length;c<b;c++)a[c]=null;return b}function Zc(a,b){a.oe||(a.oe=a.getContext,a.getContext=function(d,e){e=a.oe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Fd(c,b):0}function Fd(a,b){var c=D(8);v[c+4>>2]=bc();var d={ig:c,attributes:b,version:b.Ff,qe:a};a.canvas&&(a.canvas.xe=d);L[c]=d;("undefined"==typeof b.dg||b.dg)&&Gd(d);return c}function $c(a){Hd=L[a];g.ue=M=Hd&&Hd.qe}
function Gd(a){a||(a=Hd);if(!a.lg){a.lg=!0;var b=a.qe;sd(b);td(b);ud(b);b.se=b.getExtension("EXT_disjoint_timer_query");b.Ug=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Yc={},Dd,Hd;
function Id(a,b,c,d){if(k)return I(9,1,a,b,c,d);if(62E3!=a)return O=12296,0;for(a=1;;){b=v[d>>2];if(12440==b)a=v[d+4>>2];else if(12344==b)break;else return O=12292,0;d+=8}if(2!=a)return O=12293,0;P.Ff=a-1;P.Sg=0;pd=Zc(g.canvas,P);if(0!=pd)return O=12288,$c(pd),g.Cg=!0,Qc.forEach(function(e){e()}),$c(null),62004;O=12297;return 0}function Jd(a,b,c,d){if(k)return I(10,1,a,b,c,d);if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;O=12288;return 62006}
function Kd(a,b){if(k)return I(11,1,a,b);if(62E3!=a)return O=12296,0;if(62004!=b)return O=12294,0;a=pd;Hd===L[a]&&(Hd=null);if("object"==typeof Ld)for(var c=L[a].qe.canvas,d=0;d<Md.length;++d)Md[d].target!=c||Nd(d--);L[a]&&L[a].qe.canvas&&(L[a].qe.canvas.xe=void 0);Od(L[a].ig);L[a]=null;O=12288;ld==b&&(ld=0);return 1}function Pd(a,b){if(k)return I(12,1,a,b);if(62E3!=a)return O=12296,0;if(62006!=b)return O=12301,1;md==b&&(md=0);nd==b&&(nd=0);O=12288;return 1}
function Qd(a,b,c,d){if(k)return I(13,1,a,b,c,d);if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;if(!d)return O=12300,0;O=12288;switch(c){case 12320:return v[d>>2]=P.alpha?32:24,1;case 12321:return v[d>>2]=P.alpha?8:0,1;case 12322:return v[d>>2]=8,1;case 12323:return v[d>>2]=8,1;case 12324:return v[d>>2]=8,1;case 12325:return v[d>>2]=P.depth?24:0,1;case 12326:return v[d>>2]=P.stencil?8:0,1;case 12327:return v[d>>2]=12344,1;case 12328:return v[d>>2]=62002,1;case 12329:return v[d>>2]=0,1;case 12330:return v[d>>
2]=4096,1;case 12331:return v[d>>2]=16777216,1;case 12332:return v[d>>2]=4096,1;case 12333:return v[d>>2]=0,1;case 12334:return v[d>>2]=0,1;case 12335:return v[d>>2]=12344,1;case 12337:return v[d>>2]=P.antialias?4:0,1;case 12338:return v[d>>2]=P.antialias?1:0,1;case 12339:return v[d>>2]=4,1;case 12340:return v[d>>2]=12344,1;case 12341:case 12342:case 12343:return v[d>>2]=-1,1;case 12345:case 12346:return v[d>>2]=0,1;case 12347:return v[d>>2]=0,1;case 12348:return v[d>>2]=1;case 12349:case 12350:return v[d>>
2]=0,1;case 12351:return v[d>>2]=12430,1;case 12352:return v[d>>2]=4,1;case 12354:return v[d>>2]=0,1;default:return O=12292,0}}function Rd(a){if(k)return I(14,1,a);O=12288;return 62E3}function Sd(){return k?I(15,1):O}function Td(a,b,c){if(k)return I(16,1,a,b,c);if(62E3!=a)return O=12296,0;b&&(v[b>>2]=1);c&&(v[c>>2]=4);kd=!0;O=12288;return 1}
function Ud(a,b,c,d){if(k)return I(17,1,a,b,c,d);if(62E3!=a)return O=12296,0;if(0!=d&&62004!=d)return O=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return O=12301,0;$c(d?pd:null);ld=d;nd=b;md=c;O=12288;return 1}function Vd(a){var b=xa(a)+1,c=D(b);c&&wa(a,t,c,b);return c}
function Wd(a,b){if(k)return I(18,1,a,b);if(62E3!=a)return O=12296,0;O=12288;if(od[b])return od[b];switch(b){case 12371:a=Vd("Emscripten");break;case 12372:a=Vd("1.4 Emscripten EGL");break;case 12373:a=Vd("");break;case 12429:a=Vd("OpenGL_ES");break;default:return O=12300,0}return od[b]=a}function Xd(){if(k)return I(19,1);if(kd)if(g.ue)if(g.ue.isContextLost())O=12302;else return O=12288,1;else O=12290;else O=12289;return 0}
function Yd(a,b){if(k)return I(20,1,a,b);if(62E3!=a)return O=12296,0;0==b?tc(0,0):tc(1,b);O=12288;return 1}function Zd(a){if(k)return I(21,1,a);if(62E3!=a)return O=12296,0;nd=md=ld=0;kd=!1;O=12288;return 1}function $d(){if(k)return I(22,1);O=12288;return 1}function ae(a){if(k)return I(23,1,a);O=12288;return 1}var be=[];function ce(a,b){be.length=0;var c;for(b>>=2;c=q[a++];)b+=105!=c&b,be.push(105==c?v[b]:B[b++>>1]),++b;return be}var de=0;
function ee(){for(var a=Md.length-1;0<=a;--a)Nd(a);Md=[];U=[]}var U=[];function fe(a,b,c){function d(h,m){if(h.length!=m.length)return!1;for(var n in h)if(h[n]!=m[n])return!1;return!0}for(var e in U){var f=U[e];if(f.mf==a&&d(f.sf,c))return}U.push({mf:a,Lf:b,sf:c});U.sort(function(h,m){return h.Lf<m.Lf})}function ge(a){for(var b=0;b<U.length;++b)U[b].mf==a&&(U.splice(b,1),--b)}function he(){if(de&&ie.Fe)for(var a=0;a<U.length;++a){var b=U[a];U.splice(a,1);--a;b.mf.apply(null,b.sf)}}var Md=[];
function Nd(a){var b=Md[a];b.target.removeEventListener(b.le,b.eg,b.pe);Md.splice(a,1)}function V(a){function b(d){++de;ie=a;he();a.te(d);he();--de}if(a.re)a.eg=b,a.target.addEventListener(a.le,b,a.pe),Md.push(a),je||(Ha.push(ee),je=!0);else for(var c=0;c<Md.length;++c)Md[c].target==a.target&&Md[c].le==a.le&&Nd(c--)}function W(a,b,c,d,e){ec(function(){var f=ke(12);v[f>>2]=c;v[f+4>>2]=d;v[f+8>>2]=e;le(a,637534208,b,d,f)})}
function me(a){switch(a){case 1:return 0;case 2:return E.wf;default:return a}}function ne(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function oe(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var Ld={},je,ie,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be={},Ce=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function X(a){a=2<a?va(a):a;return Ce[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function De(a,b,c){a=X(a);if(!a||a.uf)return-4;v[b>>2]=a.width;v[c>>2]=a.height;return 0}function Ee(a,b,c){return k?I(25,1,a,b,c):De(a,b,c)}function Fe(a){return ec(function(){var b=ke(8),c=b+4,d=ke(a.id.length+1);r(a.id,d,a.id.length+1);X(d)?De(d,b,c):Ee(d,b,c);return[v[b>>2],v[c>>2]]})}
function Ge(a,b,c){a=X(a);if(!a||a.uf)return-4;var d=!1;a.xe&&a.xe.qe&&(d=a.xe.qe.getParameter(2978),d=0===d[0]&&0===d[1]&&d[2]===a.width&&d[3]===a.height);a.width=b;a.height=c;d&&a.xe.qe.viewport(0,0,b,c);return 0}function He(a,b,c){return k?I(26,1,a,b,c):Ge(a,b,c)}function Ie(a,b,c){return X(a)?Ge(a,b,c):He(a,b,c)}function Je(a,b,c){a.uf?ec(function(){var d=ke(a.id.length+1);r(a.id,d,a.id.length+1);Ie(d,b,c)}):(a.width=b,a.height=c)}
function Ke(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Je(a,d,e),a.style.width=f,a.style.height=h,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=u,a.style.paddingRight=x,a.style.paddingTop=z,a.style.paddingBottom=A,a.style.marginLeft=K,a.style.marginRight=
N,a.style.marginTop=ia,a.style.marginBottom=ja,document.body.style.margin=ig,document.documentElement.style.overflow=jg,document.body.scroll=kg,a.style.Ee=lg,a.xe&&a.xe.qe.viewport(0,0,d,e),Be.Je&&(Be.Re?W(Be.Re,Be.Je,37,0,Be.Se):J(Be.Je)(37,0,Be.Se)))}var c=Fe(a),d=c[0],e=c[1],f=a.style.width,h=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,u=a.style.paddingLeft,x=a.style.paddingRight,z=a.style.paddingTop,A=a.style.paddingBottom,K=a.style.marginLeft,N=a.style.marginRight,
ia=a.style.marginTop,ja=a.style.marginBottom,ig=document.body.style.margin,jg=document.documentElement.style.overflow,kg=document.body.scroll,lg=a.style.Ee;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Le(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Me(a){return 0>Ce.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Ne(a,b){if(0!=b.lf||0!=b.df){Ke(a);var c=b.xg?innerWidth:screen.width,d=b.xg?innerHeight:screen.height,e=Me(a),f=e.width;e=e.height;var h=Fe(a),m=h[0];h=h[1];3==b.lf?(Le(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.lf&&(c*h<m*d?(f=h*c/m,Le(a,(d-f)/2,0),d=f):(f=m*d/h,Le(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.fg&&(a.style.Ee="optimizeSpeed",
a.style.Ee="-moz-crisp-edges",a.style.Ee="-o-crisp-edges",a.style.Ee="-webkit-optimize-contrast",a.style.Ee="optimize-contrast",a.style.Ee="crisp-edges",a.style.Ee="pixelated");f=2==b.df?devicePixelRatio:1;0!=b.df&&(c=c*f|0,d=d*f|0,Je(a,c,d),a.xe&&a.xe.qe.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return oe()?-3:-1;Be=b;b.Je&&(b.Re?W(b.Re,b.Je,37,0,b.Se):J(b.Je)(37,0,b.Se));return 0}
function Oe(){if(k)return I(24,1);if(!oe())return-1;ge(Ne);var a=Ce[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0}function Pe(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.$e)a.$e();else return document.body.requestPointerLock||document.body.$e?-3:-1;return 0}
function Qe(){if(k)return I(27,1);ge(Pe);if(document.exitPointerLock)document.exitPointerLock();else if(document.oe)document.oe();else return-1;return 0}function Re(){return k?I(28,1):devicePixelRatio}function Se(a,b,c){if(k)return I(29,1,a,b,c);a=X(a);if(!a)return-4;a=Me(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0}
function Te(a,b){B[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)B[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)B[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)v[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];v[a+1296>>2]=b.connected;v[a+1300>>2]=b.index;v[a+8>>2]=b.axes.length;v[a+12>>2]=b.buttons.length;r(b.id,a+1304,64);r(b.mapping,a+1368,64)}
function Ue(a,b){if(k)return I(30,1,a,b);if(0>a||a>=pe.length)return-5;if(!pe[a])return-7;Te(b,pe[a]);return 0}function Ve(){return k?I(31,1):pe.length}function We(a,b){if(k)return I(32,1,a,b);v[a>>2]=screen.width;v[b>>2]=screen.height}var Xe=[];function Ye(a,b,c,d){for(var e=0;e<a;e++){var f=M[c](),h=f&&Ed(d);f?(f.name=h,d[h]=f):T(1282);v[b+4*e>>2]=h}}function Ze(a,b,c,d,e,f,h,m){b=Q[b];if(a=M[a](b,c))d=m&&r(a.name,m,d),e&&(v[e>>2]=d),f&&(v[f>>2]=a.size),h&&(v[h>>2]=a.type)}
function $e(a,b){w[a>>2]=b;w[a+4>>2]=(b-w[a>>2])/4294967296}
function af(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&T(1280);return;case 36345:d=0;break;case 34466:var e=M.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=M.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:T(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;case 4:t[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){T(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:T(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:$e(b,
d);break;case 0:v[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:t[b>>0]=d?1:0}}else T(1281)}function bf(a){var b=xa(a)+1,c=D(b);r(a,c,b);return c}function cf(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function df(a){var b=a.Qe,c=a.Vf,d;if(!b)for(a.Qe=b={},a.Uf={},d=0;d<M.getProgramParameter(a,35718);++d){var e=M.getActiveUniform(a,d);var f=e.name;e=e.size;var h=cf(f);h=0<h?f.slice(0,h):f;var m=a.nf;a.nf+=e;c[h]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Uf[m++]=h}}
function Y(a){var b=M.Zf;if(b){var c=b.Qe[a];"number"==typeof c&&(b.Qe[a]=c=M.getUniformLocation(b,b.Uf[a]+(0<c?"["+c+"]":"")));return c}T(1282)}function ef(a,b,c,d){if(c)if(a=Q[a],df(a),a=M.getUniform(a,Y(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else T(1281)}
function ff(a,b,c,d){if(c)if(a=M.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:y[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b])}else T(1281)}
function gf(a,b,c,d,e){a-=5120;a=1==a?q:4==a?v:6==a?y:5==a||28922==a?w:Aa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Cd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var hf=[],jf=[];function I(a,b){var c=arguments.length-2,d=arguments;return ec(()=>{for(var e=ke(8*c),f=e>>3,h=0;h<c;h++)B[f+h]=d[2+h];return kf(a,c,e,b)})}var lf=[];
function mf(a,b){if(!oe())return-1;a=X(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?de&&ie.Fe?Ne(a,b):b.cg?(fe(Ne,1,[a,b]),1):-2:-3:-4}function nf(a,b,c){return k?I(33,1,a,b,c):mf(a,{lf:v[c>>2],df:v[c+4>>2],fg:v[c+8>>2],cg:b,Re:v[c+20>>2],Je:v[c+12>>2],Se:v[c+16>>2]})}function of(a,b){if(k)return I(34,1,a,b);a=X(a);return a?a.requestPointerLock||a.$e?de&&ie.Fe?Pe(a):b?(fe(Pe,2,[a]),1):-2:-1:-4}
function pf(){return k?I(35,1):(pe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1}function qf(a,b){var c={target:X(2),le:"beforeunload",re:b,te:function(d){d=d||event;var e=J(b)(28,0,a);e&&(e=va(e));if(e)return d.preventDefault(),d.returnValue=e},pe:!0};V(c)}function rf(a,b,c){if(k)return I(36,1,a,b,c);if("undefined"==typeof onbeforeunload)return-1;if(1!==c)return-5;qf(a,b);return 0}
function sf(a,b,c,d,e,f,h){h=me(h);qe||(qe=D(256));a={target:X(a),le:f,re:d,te:function(m){m=m||event;var n=ne(m.target),u=m.target.id?m.target.id:"",x=h?D(256):qe;r(n,x+0,128);r(u,x+128,128);h?W(h,d,e,x,b):J(d)(e,x,b)&&m.preventDefault()},pe:c};V(a)}function tf(a,b,c,d,e){if(k)return I(37,1,a,b,c,d,e);sf(a,b,c,d,12,"blur",e);return 0}function uf(a,b,c){if(k)return I(38,1,a,b,c);a=X(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0}
function vf(a,b,c,d,e){if(k)return I(39,1,a,b,c,d,e);sf(a,b,c,d,13,"focus",e);return 0}
function wf(a,b,c,d,e,f){f=me(f);se||(se=D(280));V({target:a,le:e,re:d,te:function(h){h=h||event;var m=f?D(280):se,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,u=!!n;v[m>>2]=u;v[m+4>>2]=oe();var x=u?n:re,z=x&&x.id?x.id:"";r(ne(x),m+8,128);r(z,m+136,128);v[m+264>>2]=x?x.clientWidth:0;v[m+268>>2]=x?x.clientHeight:0;v[m+272>>2]=screen.width;v[m+276>>2]=screen.height;u&&(re=n);f?W(f,d,19,m,b):J(d)(19,m,b)&&h.preventDefault()},
pe:c})}function xf(a,b,c,d,e){if(k)return I(40,1,a,b,c,d,e);if(!oe())return-1;a=X(a);if(!a)return-4;wf(a,b,c,d,"fullscreenchange",e);wf(a,b,c,d,"webkitfullscreenchange",e);return 0}function yf(a,b,c,d,e,f){f=me(f);te||(te=D(1432));b={target:X(2),Fe:!0,le:e,re:c,te:function(h){h=h||event;var m=f?D(1432):te;Te(m,h.gamepad);f?W(f,c,d,m,a):J(c)(d,m,a)&&h.preventDefault()},pe:b};V(b)}
function zf(a,b,c,d){if(k)return I(41,1,a,b,c,d);if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;yf(a,b,c,26,"gamepadconnected",d);return 0}function Af(a,b,c,d){if(k)return I(42,1,a,b,c,d);if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;yf(a,b,c,27,"gamepaddisconnected",d);return 0}
function Bf(a,b,c,d,e,f,h){h=me(h);ue||(ue=D(176));a={target:X(a),Fe:!0,le:f,re:d,te:function(m){var n=h?D(176):ue;B[n>>3]=m.timeStamp;var u=n>>2;v[u+2]=m.location;v[u+3]=m.ctrlKey;v[u+4]=m.shiftKey;v[u+5]=m.altKey;v[u+6]=m.metaKey;v[u+7]=m.repeat;v[u+8]=m.charCode;v[u+9]=m.keyCode;v[u+10]=m.which;r(m.key||"",n+44,32);r(m.code||"",n+76,32);r(m.char||"",n+108,32);r(m.locale||"",n+140,32);h?W(h,d,e,n,b):J(d)(e,n,b)&&m.preventDefault()},pe:c};V(a)}
function Cf(a,b,c,d,e){if(k)return I(43,1,a,b,c,d,e);Bf(a,b,c,d,2,"keydown",e);return 0}function Df(a,b,c,d,e){if(k)return I(44,1,a,b,c,d,e);Bf(a,b,c,d,1,"keypress",e);return 0}function Ef(a,b,c,d,e){if(k)return I(45,1,a,b,c,d,e);Bf(a,b,c,d,3,"keyup",e);return 0}
function Ff(a,b,c){B[a>>3]=b.timeStamp;a>>=2;v[a+2]=b.screenX;v[a+3]=b.screenY;v[a+4]=b.clientX;v[a+5]=b.clientY;v[a+6]=b.ctrlKey;v[a+7]=b.shiftKey;v[a+8]=b.altKey;v[a+9]=b.metaKey;za[2*a+20]=b.button;za[2*a+21]=b.buttons;v[a+11]=b.movementX;v[a+12]=b.movementY;c=Me(c);v[a+13]=b.clientX-c.left;v[a+14]=b.clientY-c.top}
function Gf(a,b,c,d,e,f,h){h=me(h);ve||(ve=D(72));a=X(a);V({target:a,Fe:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,le:f,re:d,te:function(m){m=m||event;Ff(ve,m,a);if(h){var n=D(72);Ff(n,m,a);W(h,d,e,n,b)}else J(d)(e,ve,b)&&m.preventDefault()},pe:c})}function Hf(a,b,c,d,e){if(k)return I(46,1,a,b,c,d,e);Gf(a,b,c,d,5,"mousedown",e);return 0}function If(a,b,c,d,e){if(k)return I(47,1,a,b,c,d,e);Gf(a,b,c,d,33,"mouseenter",e);return 0}
function Jf(a,b,c,d,e){if(k)return I(48,1,a,b,c,d,e);Gf(a,b,c,d,34,"mouseleave",e);return 0}function Kf(a,b,c,d,e){if(k)return I(49,1,a,b,c,d,e);Gf(a,b,c,d,8,"mousemove",e);return 0}function Lf(a,b,c,d,e){if(k)return I(50,1,a,b,c,d,e);Gf(a,b,c,d,6,"mouseup",e);return 0}
function Mf(a,b,c,d,e,f){f=me(f);we||(we=D(260));V({target:a,le:e,re:d,te:function(h){h=h||event;var m=f?D(260):we,n=document.pointerLockElement||document.ff||document.Cf||document.Bf;v[m>>2]=!!n;var u=n&&n.id?n.id:"";r(ne(n),m+4,128);r(u,m+132,128);f?W(f,d,20,m,b):J(d)(20,m,b)&&h.preventDefault()},pe:c})}
function Nf(a,b,c,d,e){if(k)return I(51,1,a,b,c,d,e);if(!document||!document.body||!(document.body.requestPointerLock||document.body.oe||document.body.ff||document.body.$e))return-1;a=X(a);if(!a)return-4;Mf(a,b,c,d,"pointerlockchange",e);Mf(a,b,c,d,"mozpointerlockchange",e);Mf(a,b,c,d,"webkitpointerlockchange",e);Mf(a,b,c,d,"mspointerlockchange",e);return 0}
function Of(a,b,c,d,e){e=me(e);xe||(xe=D(36));a=X(a);V({target:a,le:"resize",re:d,te:function(f){f=f||event;if(f.target==a){var h=document.body;if(h){var m=e?D(36):xe;v[m>>2]=f.detail;v[m+4>>2]=h.clientWidth;v[m+8>>2]=h.clientHeight;v[m+12>>2]=innerWidth;v[m+16>>2]=innerHeight;v[m+20>>2]=outerWidth;v[m+24>>2]=outerHeight;v[m+28>>2]=pageXOffset;v[m+32>>2]=pageYOffset;e?W(e,d,10,m,b):J(d)(10,m,b)&&f.preventDefault()}}},pe:c})}
function Pf(a,b,c,d,e){if(k)return I(52,1,a,b,c,d,e);Of(a,b,c,d,e);return 0}
function Qf(a,b,c,d,e,f,h){h=me(h);ye||(ye=D(1696));a=X(a);V({target:a,Fe:"touchstart"==f||"touchend"==f,le:f,re:d,te:function(m){for(var n,u={},x=m.touches,z=0;z<x.length;++z)n=x[z],n.Df=n.Kf=0,u[n.identifier]=n;for(z=0;z<m.changedTouches.length;++z)n=m.changedTouches[z],n.Df=1,u[n.identifier]=n;for(z=0;z<m.targetTouches.length;++z)u[m.targetTouches[z].identifier].Kf=1;x=h?D(1696):ye;B[x>>3]=m.timeStamp;var A=x>>2;v[A+3]=m.ctrlKey;v[A+4]=m.shiftKey;v[A+5]=m.altKey;v[A+6]=m.metaKey;A+=7;var K=Me(a),
N=0;for(z in u)if(n=u[z],v[A]=n.identifier,v[A+1]=n.screenX,v[A+2]=n.screenY,v[A+3]=n.clientX,v[A+4]=n.clientY,v[A+5]=n.pageX,v[A+6]=n.pageY,v[A+7]=n.Df,v[A+8]=n.Kf,v[A+9]=n.clientX-K.left,v[A+10]=n.clientY-K.top,A+=13,31<++N)break;v[x+8>>2]=N;h?W(h,d,e,x,b):J(d)(e,x,b)&&m.preventDefault()},pe:c})}function Rf(a,b,c,d,e){if(k)return I(53,1,a,b,c,d,e);Qf(a,b,c,d,25,"touchcancel",e);return 0}function Sf(a,b,c,d,e){if(k)return I(54,1,a,b,c,d,e);Qf(a,b,c,d,23,"touchend",e);return 0}
function Tf(a,b,c,d,e){if(k)return I(55,1,a,b,c,d,e);Qf(a,b,c,d,24,"touchmove",e);return 0}function Uf(a,b,c,d,e){if(k)return I(56,1,a,b,c,d,e);Qf(a,b,c,d,22,"touchstart",e);return 0}function Vf(a,b,c,d){var e=Ce[1];d=me(d);ze||(ze=D(8));V({target:e,le:"visibilitychange",re:c,te:function(f){f=f||event;var h=d?D(8):ze,m=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);v[h>>2]=document.hidden;v[h+4>>2]=m;d?W(d,c,21,h,a):J(c)(21,h,a)&&f.preventDefault()},pe:b})}
function Wf(a,b,c,d){if(k)return I(57,1,a,b,c,d);if(!Ce[1])return-4;Vf(a,b,c,d);return 0}function Xf(a,b,c,d,e){e=me(e);Ae||(Ae=D(104));V({target:a,Fe:!0,le:"wheel",re:d,te:function(f){f=f||event;var h=e?D(104):Ae;Ff(h,f,a);B[h+72>>3]=f.deltaX;B[h+80>>3]=f.deltaY;B[h+88>>3]=f.deltaZ;v[h+96>>2]=f.deltaMode;e?W(e,d,9,h,b):J(d)(9,h,b)&&f.preventDefault()},pe:c})}function Yf(a,b,c,d,e){if(k)return I(58,1,a,b,c,d,e);a=X(a);return"undefined"!=typeof a.onwheel?(Xf(a,b,c,d,e),0):-1}
function Zf(a){if(k)return I(59,1,a);na(va(a))}var $f={};function ag(){if(!bg){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in $f)void 0===$f[b]?delete a[b]:a[b]=$f[b];var c=[];for(b in a)c.push(b+"="+a[b]);bg=c}return bg}var bg;
function cg(a,b){if(k)return I(60,1,a,b);var c=0;ag().forEach(function(d,e){var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)t[e++>>0]=d.charCodeAt(f);t[e>>0]=0;c+=d.length+1});return 0}function dg(a,b){if(k)return I(61,1,a,b);var c=ag();w[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});w[b>>2]=d;return 0}
function eg(a){if(k)return I(62,1,a);try{var b=Wb(a);if(null===b.Ce)throw new F(8);b.gf&&(b.gf=null);try{b.he.close&&b.he.close(b)}catch(c){throw c;}finally{yb[b.Ce]=null}b.Ce=null;return 0}catch(c){if("undefined"==typeof Tb||!(c instanceof F))throw c;return c.Ge}}
function fg(a,b,c,d){if(k)return I(63,1,a,b,c,d);try{a:{var e=Wb(a);a=b;for(var f=b=0;f<c;f++){var h=w[a>>2],m=w[a+4>>2];a+=8;var n=e,u=h,x=m,z=void 0;if(0>x||0>z)throw new F(28);if(null===n.Ce)throw new F(8);if(1===(n.flags&2097155))throw new F(8);if(16384===(n.node.mode&61440))throw new F(31);if(!n.he.read)throw new F(28);var A="undefined"!=typeof z;if(!A)z=n.position;else if(!n.seekable)throw new F(70);var K=n.he.read(n,t,u,x,z);A||(n.position+=K);var N=K;if(0>N){var ia=-1;break a}b+=N;if(N<m)break}ia=
b}w[d>>2]=ia;return 0}catch(ja){if("undefined"==typeof Tb||!(ja instanceof F))throw ja;return ja.Ge}}
function gg(a,b,c,d,e){if(k)return I(64,1,a,b,c,d,e);try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var f=Wb(a);Qb(f,b,d);Za=[f.position>>>0,(C=f.position,1<=+Math.abs(C)?0<C?(Math.min(+Math.floor(C/4294967296),4294967295)|0)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];v[e>>2]=Za[0];v[e+4>>2]=Za[1];f.gf&&0===b&&0===d&&(f.gf=null);return 0}catch(h){if("undefined"==typeof Tb||!(h instanceof F))throw h;return h.Ge}}
function hg(a,b,c,d){if(k)return I(65,1,a,b,c,d);try{a:{var e=Wb(a);a=b;for(var f=b=0;f<c;f++){var h=w[a>>2],m=w[a+4>>2];a+=8;var n=e,u=h,x=m,z=void 0;if(0>x||0>z)throw new F(28);if(null===n.Ce)throw new F(8);if(0===(n.flags&2097155))throw new F(8);if(16384===(n.node.mode&61440))throw new F(31);if(!n.he.write)throw new F(28);n.seekable&&n.flags&1024&&Qb(n,0,2);var A="undefined"!=typeof z;if(!A)z=n.position;else if(!n.seekable)throw new F(70);var K=n.he.write(n,t,u,x,z,void 0);A||(n.position+=K);var N=
K;if(0>N){var ia=-1;break a}b+=N}ia=b}w[d>>2]=ia;return 0}catch(ja){if("undefined"==typeof Tb||!(ja instanceof F))throw ja;return ja.Ge}}function mg(a,b){mg.Mf||(mg.Mf=kb());for(var c=0;c<b;c++)t[a+c>>0]=mg.Mf();return 0}E.hf();function Gb(a,b,c,d){a||(a=this);this.parent=a;this.ye=a.ye;this.Ze=null;this.id=zb++;this.name=b;this.mode=c;this.ge={};this.he={};this.af=d}
Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});La();Ab=Array(4096);Nb(G,"/");H("/tmp",16895,0);H("/home",16895,0);H("/home/web_user",16895,0);
(()=>{H("/dev",16895,0);ob(259,{read:()=>0,write:(b,c,d,e)=>e});Ob("/dev/null",259);nb(1280,qb);nb(1536,rb);Ob("/dev/tty",1280);Ob("/dev/tty1",1536);var a=kb();Ma("random",a);Ma("urandom",a);H("/dev/shm",16895,0);H("/dev/shm/tmp",16895,0)})();(()=>{H("/proc",16895,0);var a=H("/proc/self",16895,0);H("/proc/self/fd",16895,0);Nb({ye:()=>{var b=tb(a,"fd",16895,73);b.ge={Le:(c,d)=>{var e=yb[+d];if(!e)throw new F(8);c={parent:null,ye:{Hf:"fake"},ge:{Me:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
g.requestFullscreen=function(a,b){dd(a,b)};g.requestAnimationFrame=function(a){Cc(a)};g.setCanvasSize=function(a,b,c){fd(g.canvas,a,b);c||gd()};g.pauseMainLoop=function(){yc=null;Fc++};g.resumeMainLoop=function(){Fc++;var a=uc,b=vc,c=wc;wc=null;Dc(c,0,!1,Ec,!0);tc(a,b);yc()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Xc(a,b,c,d)};for(var M,Z=0;32>Z;++Z)Xe.push(Array(Z));
var ng=new Float32Array(288);for(Z=0;288>Z;++Z)hf[Z]=ng.subarray(0,Z+1);var og=new Int32Array(288);for(Z=0;288>Z;++Z)jf[Z]=og.subarray(0,Z+1);
var pg=[null,Xb,Zb,mc,oc,qc,rc,qd,rd,Id,Jd,Kd,Pd,Qd,Rd,Sd,Td,Ud,Wd,Xd,Yd,Zd,$d,ae,Oe,Ee,He,Qe,Re,Se,Ue,Ve,We,nf,of,pf,rf,tf,uf,vf,xf,zf,Af,Cf,Df,Ef,Hf,If,Jf,Kf,Lf,Nf,Pf,Rf,Sf,Tf,Uf,Wf,Yf,Zf,cg,dg,eg,fg,gg,hg],rg={Sa:function(a,b){J(a)(b)},I:function(a){return D(a+24)+24},E:function(a,b,c){(new kc(a)).hf(b,c);lc++;throw a;},Za:function(a){qg(a,!fa,1,!ea);E.Sf()},J:function(a){k?postMessage({cmd:"cleanupThread",thread:a}):eb(a)},Ta:nc,M:oc,db:qc,fb:rc,jb:function(){},kb:function(){p("To use dlopen, you need enable dynamic linking, see https://github.com/emscripten-core/emscripten/wiki/Linking")},
ib:function(){return Date.now()},Ua:function(){return 2097152},hb:function(){return!0},Va:function(a,b,c,d){if(a==b)setTimeout(()=>cc(d));else if(k)postMessage({targetThread:a,cmd:"processProxyingQueue",queue:d});else{a=E.Ae[a];if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:d})}return 1},Ya:function(){return-1},j:function(){p("")},La:qd,qc:rd,Wb:Id,zb:Jd,Kb:Kd,ob:Pd,fc:Qd,N:Rd,Ja:Sd,Mc:Td,eb:Ud,Ka:Wd,Xa:Xd,Pa:Yd,Bc:Zd,Ma:$d,Na:ae,Ga:function(a,b,c){b=ce(b,c);return cb[a].apply(null,
b)},b:function(a,b,c){b=ce(b,c);return k?I.apply(null,[-1-a,1].concat(b)):cb[a].apply(null,b)},Jd:function(){yc=null;Fc++;wc=null},K:function(){fa||Mc("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")},Da:Oe,Ha:Qe,f:Re,d:Se,Z:Ue,c:Ac,ia:Ve,Ia:We,ga:function(a){M.activeTexture(a)},fa:function(a,b){M.attachShader(Q[a],R[b])},ya:function(a,b){M.se.beginQueryEXT(a,S[b])},ea:function(a,b,c){M.bindAttribLocation(Q[a],
b,va(c))},da:function(a,b){M.bindBuffer(a,wd[b])},ca:function(a,b){M.bindFramebuffer(a,xd[b])},ba:function(a,b){M.bindRenderbuffer(a,yd[b])},aa:function(a,b){M.bindTexture(a,zd[b])},pa:function(a){M.bindVertexArray(Ad[a])},$:function(a,b,c,d){M.blendColor(a,b,c,d)},_:function(a){M.blendEquation(a)},Y:function(a,b){M.blendEquationSeparate(a,b)},X:function(a,b){M.blendFunc(a,b)},W:function(a,b,c,d){M.blendFuncSeparate(a,b,c,d)},V:function(a,b,c,d){M.bufferData(a,c?q.subarray(c,c+b):b,d)},U:function(a,
b,c,d){M.bufferSubData(a,b,q.subarray(d,d+c))},T:function(a){return M.checkFramebufferStatus(a)},S:function(a){M.clear(a)},R:function(a,b,c,d){M.clearColor(a,b,c,d)},Q:function(a){M.clearDepth(a)},P:function(a){M.clearStencil(a)},Id:function(a,b,c,d){M.colorMask(!!a,!!b,!!c,!!d)},Hd:function(a){M.compileShader(R[a])},Gd:function(a,b,c,d,e,f,h,m){M.compressedTexImage2D(a,b,c,d,e,f,m?q.subarray(m,m+h):null)},Fd:function(a,b,c,d,e,f,h,m,n){M.compressedTexSubImage2D(a,b,c,d,e,f,h,n?q.subarray(n,n+m):
null)},Ed:function(a,b,c,d,e,f,h,m){M.copyTexImage2D(a,b,c,d,e,f,h,m)},Dd:function(a,b,c,d,e,f,h,m){M.copyTexSubImage2D(a,b,c,d,e,f,h,m)},Cd:function(){var a=Ed(Q),b=M.createProgram();b.name=a;b.We=b.Ue=b.Ve=0;b.nf=1;Q[a]=b;return a},Bd:function(a){var b=Ed(R);R[b]=M.createShader(a);return b},Ad:function(a){M.cullFace(a)},zd:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=wd[d];e&&(M.deleteBuffer(e),e.name=0,wd[d]=null)}},yd:function(a,b){for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=xd[d];e&&(M.deleteFramebuffer(e),
e.name=0,xd[d]=null)}},xd:function(a){if(a){var b=Q[a];b?(M.deleteProgram(b),b.name=0,Q[a]=null):T(1281)}},Aa:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(M.se.deleteQueryEXT(e),S[d]=null)}},wd:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=yd[d];e&&(M.deleteRenderbuffer(e),e.name=0,yd[d]=null)}},vd:function(a){if(a){var b=R[a];b?(M.deleteShader(b),R[a]=null):T(1281)}},ud:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=zd[d];e&&(M.deleteTexture(e),e.name=0,zd[d]=
null)}},oa:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];M.deleteVertexArray(Ad[d]);Ad[d]=null}},td:function(a){M.depthFunc(a)},sd:function(a){M.depthMask(!!a)},rd:function(a,b){M.depthRange(a,b)},qd:function(a,b){M.detachShader(Q[a],R[b])},pd:function(a){M.disable(a)},od:function(a){M.disableVertexAttribArray(a)},nd:function(a,b,c){M.drawArrays(a,b,c)},ka:function(a,b,c,d){M.drawArraysInstanced(a,b,c,d)},la:function(a,b){for(var c=Xe[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];M.drawBuffers(c)},md:function(a,
b,c,d){M.drawElements(a,b,c,d)},ja:function(a,b,c,d,e){M.drawElementsInstanced(a,b,c,d,e)},ld:function(a){M.enable(a)},kd:function(a){M.enableVertexAttribArray(a)},xa:function(a){M.se.endQueryEXT(a)},jd:function(){M.finish()},id:function(){M.flush()},hd:function(a,b,c,d){M.framebufferRenderbuffer(a,b,c,yd[d])},gd:function(a,b,c,d,e){M.framebufferTexture2D(a,b,c,zd[d],e)},fd:function(a){M.frontFace(a)},ed:function(a,b){Ye(a,b,"createBuffer",wd)},cd:function(a,b){Ye(a,b,"createFramebuffer",xd)},Ba:function(a,
b){for(var c=0;c<a;c++){var d=M.se.createQueryEXT();if(!d){for(T(1282);c<a;)v[b+4*c++>>2]=0;break}var e=Ed(S);d.name=e;S[e]=d;v[b+4*c>>2]=e}},bd:function(a,b){Ye(a,b,"createRenderbuffer",yd)},ad:function(a,b){Ye(a,b,"createTexture",zd)},na:function(a,b){Ye(a,b,"createVertexArray",Ad)},dd:function(a){M.generateMipmap(a)},$c:function(a,b,c,d,e,f,h){Ze("getActiveAttrib",a,b,c,d,e,f,h)},_c:function(a,b,c,d,e,f,h){Ze("getActiveUniform",a,b,c,d,e,f,h)},Zc:function(a,b,c,d){a=M.getAttachedShaders(Q[a]);
var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=R.indexOf(a[b])},Yc:function(a,b){return M.getAttribLocation(Q[a],va(b))},Xc:function(a,b){af(a,b,4)},Wc:function(a,b,c){c?v[c>>2]=M.getBufferParameter(a,b):T(1281)},Vc:function(){var a=M.getError()||Dd;Dd=0;return a},Uc:function(a,b){af(a,b,2)},Tc:function(a,b,c,d){a=M.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},Sc:function(a,b){af(a,b,0)},Qc:function(a,
b,c,d){a=M.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?r(a,d,b):0;c&&(v[c>>2]=b)},Rc:function(a,b,c){if(c)if(a>=vd)T(1281);else if(a=Q[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.We)for(b=0;b<M.getProgramParameter(a,35718);++b)a.We=Math.max(a.We,M.getActiveUniform(a,b).name.length+1);v[c>>2]=a.We}else if(35722==b){if(!a.Ue)for(b=0;b<M.getProgramParameter(a,35721);++b)a.Ue=Math.max(a.Ue,M.getActiveAttrib(a,b).name.length+
1);v[c>>2]=a.Ue}else if(35381==b){if(!a.Ve)for(b=0;b<M.getProgramParameter(a,35382);++b)a.Ve=Math.max(a.Ve,M.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Ve}else v[c>>2]=M.getProgramParameter(a,b);else T(1281)},ra:function(a,b,c){if(c){a=M.se.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;$e(c,d)}else T(1281)},ua:function(a,b,c){if(c){a=M.se.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},qa:function(a,b,c){if(c){a=M.se.getQueryObjectEXT(S[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;$e(c,d)}else T(1281)},sa:function(a,b,c){if(c){a=M.se.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},va:function(a,b,c){c?v[c>>2]=M.se.getQueryEXT(a,b):T(1281)},Pc:function(a,b,c){c?v[c>>2]=M.getRenderbufferParameter(a,b):T(1281)},Nc:function(a,b,c,d){a=M.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?r(a,d,b):0;c&&(v[c>>2]=b)},Lc:function(a,b,c,d){a=M.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;
v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},Kc:function(a,b,c,d){if(a=M.getShaderSource(R[a]))b=0<b&&d?r(a,d,b):0,c&&(v[c>>2]=b)},Oc:function(a,b,c){c?35716==b?(a=M.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=M.getShaderParameter(R[a],b):T(1281)},Jc:function(a){var b=Bd[a];if(!b){switch(a){case 7939:b=M.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=bf(b.join(" "));break;
case 7936:case 7937:case 37445:case 37446:(b=M.getParameter(a))||T(1280);b=b&&bf(b);break;case 7938:b=bf("OpenGL ES 2.0 ("+M.getParameter(7938)+")");break;case 35724:b=M.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=bf(b);break;default:T(1280)}Bd[a]=b}return b},Ic:function(a,b,c){c?y[c>>2]=M.getTexParameter(a,b):T(1281)},Hc:function(a,b,c){c?v[c>>2]=M.getTexParameter(a,b):T(1281)},
Ec:function(a,b){b=va(b);if(a=Q[a]){df(a);var c=a.Qe,d=0,e=b,f=cf(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Vf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else T(1281);return-1},Gc:function(a,b,c){ef(a,b,c,2)},Fc:function(a,b,c){ef(a,b,c,0)},Ac:function(a,b,c){c?v[c>>2]=M.getVertexAttribOffset(a,b):T(1281)},Dc:function(a,b,c){ff(a,b,c,2)},Cc:function(a,b,c){ff(a,b,c,5)},zc:function(a,b){M.hint(a,b)},yc:function(a){return(a=wd[a])?M.isBuffer(a):0},xc:function(a){return M.isEnabled(a)},
wc:function(a){return(a=xd[a])?M.isFramebuffer(a):0},vc:function(a){return(a=Q[a])?M.isProgram(a):0},za:function(a){return(a=S[a])?M.se.isQueryEXT(a):0},uc:function(a){return(a=yd[a])?M.isRenderbuffer(a):0},tc:function(a){return(a=R[a])?M.isShader(a):0},sc:function(a){return(a=zd[a])?M.isTexture(a):0},ma:function(a){return(a=Ad[a])?M.isVertexArray(a):0},rc:function(a){M.lineWidth(a)},pc:function(a){a=Q[a];M.linkProgram(a);a.Qe=0;a.Vf={}},oc:function(a,b){3317==a&&(Cd=b);M.pixelStorei(a,b)},nc:function(a,
b){M.polygonOffset(a,b)},wa:function(a,b){M.se.queryCounterEXT(S[a],b)},mc:function(a,b,c,d,e,f,h){(h=gf(f,e,c,d,h))?M.readPixels(a,b,c,d,e,f,h):T(1280)},lc:function(){},kc:function(a,b,c,d){M.renderbufferStorage(a,b,c,d)},jc:function(a,b){M.sampleCoverage(a,!!b)},ic:function(a,b,c,d){M.scissor(a,b,c,d)},hc:function(){T(1280)},gc:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?v[d+4*f>>2]:-1;e+=va(v[c+4*f>>2],0>h?void 0:h)}M.shaderSource(R[a],e)},ec:function(a,b,c){M.stencilFunc(a,b,c)},dc:function(a,
b,c,d){M.stencilFuncSeparate(a,b,c,d)},cc:function(a){M.stencilMask(a)},bc:function(a,b){M.stencilMaskSeparate(a,b)},ac:function(a,b,c){M.stencilOp(a,b,c)},$b:function(a,b,c,d){M.stencilOpSeparate(a,b,c,d)},_b:function(a,b,c,d,e,f,h,m,n){M.texImage2D(a,b,c,d,e,f,h,m,n?gf(m,h,d,e,n):null)},Zb:function(a,b,c){M.texParameterf(a,b,c)},Yb:function(a,b,c){M.texParameterf(a,b,y[c>>2])},Xb:function(a,b,c){M.texParameteri(a,b,c)},Vb:function(a,b,c){M.texParameteri(a,b,v[c>>2])},Ub:function(a,b,c,d,e,f,h,m,
n){var u=null;n&&(u=gf(m,h,e,f,n));M.texSubImage2D(a,b,c,d,e,f,h,m,u)},Tb:function(a,b){M.uniform1f(Y(a),b)},Sb:function(a,b,c){if(288>=b)for(var d=hf[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);M.uniform1fv(Y(a),d)},Rb:function(a,b){M.uniform1i(Y(a),b)},Qb:function(a,b,c){if(288>=b)for(var d=jf[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);M.uniform1iv(Y(a),d)},Pb:function(a,b,c){M.uniform2f(Y(a),b,c)},Ob:function(a,b,c){if(144>=b)for(var d=hf[2*b-1],e=
0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);M.uniform2fv(Y(a),d)},Nb:function(a,b,c){M.uniform2i(Y(a),b,c)},Mb:function(a,b,c){if(144>=b)for(var d=jf[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);M.uniform2iv(Y(a),d)},Jb:function(a,b,c,d){M.uniform3f(Y(a),b,c,d)},Ib:function(a,b,c){if(96>=b)for(var d=hf[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>
2,c+12*b>>2);M.uniform3fv(Y(a),d)},Hb:function(a,b,c,d){M.uniform3i(Y(a),b,c,d)},Gb:function(a,b,c){if(96>=b)for(var d=jf[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);M.uniform3iv(Y(a),d)},Fb:function(a,b,c,d,e){M.uniform4f(Y(a),b,c,d,e)},Eb:function(a,b,c){if(72>=b){var d=hf[4*b-1];c>>=2;for(var e=0;e<4*b;e+=4){var f=c+e;d[e]=y[f];d[e+1]=y[f+1];d[e+2]=y[f+2];d[e+3]=y[f+3]}}else d=y.subarray(c>>2,c+16*b>>2);M.uniform4fv(Y(a),
d)},Db:function(a,b,c,d,e){M.uniform4i(Y(a),b,c,d,e)},Cb:function(a,b,c){if(72>=b)for(var d=jf[4*b-1],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);M.uniform4iv(Y(a),d)},Bb:function(a,b,c,d){if(72>=b)for(var e=hf[4*b-1],f=0;f<4*b;f+=4)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);M.uniformMatrix2fv(Y(a),!!c,e)},Ab:function(a,b,c,d){if(32>=
b)for(var e=hf[9*b-1],f=0;f<9*b;f+=9)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2];else e=y.subarray(d>>2,d+36*b>>2);M.uniformMatrix3fv(Y(a),!!c,e)},yb:function(a,b,c,d){if(18>=b){var e=hf[16*b-1];d>>=2;for(var f=0;f<16*b;f+=16){var h=d+f;e[f]=y[h];e[f+1]=y[h+1];e[f+2]=y[h+2];e[f+3]=y[h+3];e[f+4]=y[h+4];e[f+5]=y[h+5];e[f+6]=y[h+6];e[f+7]=
y[h+7];e[f+8]=y[h+8];e[f+9]=y[h+9];e[f+10]=y[h+10];e[f+11]=y[h+11];e[f+12]=y[h+12];e[f+13]=y[h+13];e[f+14]=y[h+14];e[f+15]=y[h+15]}}else e=y.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(Y(a),!!c,e)},xb:function(a){a=Q[a];M.useProgram(a);M.Zf=a},wb:function(a){M.validateProgram(Q[a])},vb:function(a,b){M.vertexAttrib1f(a,b)},ub:function(a,b){M.vertexAttrib1f(a,y[b>>2])},tb:function(a,b,c){M.vertexAttrib2f(a,b,c)},sb:function(a,b){M.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},rb:function(a,b,c,d){M.vertexAttrib3f(a,
b,c,d)},qb:function(a,b){M.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},pb:function(a,b,c,d,e){M.vertexAttrib4f(a,b,c,d,e)},nb:function(a,b){M.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},ha:function(a,b){M.vertexAttribDivisor(a,b)},mb:function(a,b,c,d,e,f){M.vertexAttribPointer(a,b,c,!!d,e,f)},lb:function(a,b,c,d){M.viewport(a,b,c,d)},l:function(){return 0},ab:function(a,b,c){q.copyWithin(a,b,b+c)},Wa:function(a,b,c){lf.length=b;c>>=3;for(var d=0;d<b;d++)lf[d]=B[c+d];return(0>a?cb[-a-
1]:pg[a]).apply(null,lf)},Ea:nf,H:of,Ra:function(){p("OOM")},Ca:function(){return noExitRuntime},ta:pf,m:rf,y:tf,e:Ie,i:uf,z:vf,p:xf,h:zf,g:Af,s:Cf,q:Df,r:Ef,Lb:function(a,b,c){a=J(a);Dc(a,b,c)},F:Hf,C:If,B:Jf,G:Kf,D:Lf,t:Nf,o:Pf,u:Rf,w:Sf,v:Tf,x:Uf,n:Wf,A:Yf,Fa:Zf,k:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},gb:function(){throw"unwind";},_a:cg,$a:dg,O:Yb,L:eg,cb:fg,Oa:gg,bb:hg,Qa:mg,a:qa};
(function(){function a(e,f){g.asm=e.exports;E.Tf.push(g.asm.Rd);Da=g.asm.Md;Fa.unshift(g.asm.Kd);ra=f;if(!k){var h=E.Be.length;E.Be.forEach(function(m){E.Ef(m,function(){if(!--h&&(Sa--,g.monitorRunDependencies&&g.monitorRunDependencies(Sa),0==Sa&&(null!==Ta&&(clearInterval(Ta),Ta=null),Ua))){var n=Ua;Ua=null;n()}})})}}function b(e){a(e.instance,e.module)}function c(e){return Ya().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){l("failed to asynchronously prepare wasm: "+
f);p(f)})}var d={a:rg};k||(Sa++,g.monitorRunDependencies&&g.monitorRunDependencies(Sa));if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return pa||"function"!=typeof WebAssembly.instantiateStreaming||Va()||"function"!=typeof fetch?c(b):fetch(Wa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){l("wasm streaming compile failed: "+f);l("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.Kd).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Ld).apply(null,arguments)};
var Od=g._free=function(){return(Od=g._free=g.asm.Nd).apply(null,arguments)},D=g._malloc=function(){return(D=g._malloc=g.asm.Od).apply(null,arguments)},bc=g._pthread_self=function(){return(bc=g._pthread_self=g.asm.Pd).apply(null,arguments)},pc=g.___errno_location=function(){return(pc=g.___errno_location=g.asm.Qd).apply(null,arguments)};g.__emscripten_tls_init=function(){return(g.__emscripten_tls_init=g.asm.Rd).apply(null,arguments)};
g.__emscripten_proxy_main=function(){return(g.__emscripten_proxy_main=g.asm.Sd).apply(null,arguments)};var qg=g.__emscripten_thread_init=function(){return(qg=g.__emscripten_thread_init=g.asm.Td).apply(null,arguments)};g.__emscripten_thread_crashed=function(){return(g.__emscripten_thread_crashed=g.asm.Ud).apply(null,arguments)};
var kf=g._emscripten_run_in_main_runtime_thread_js=function(){return(kf=g._emscripten_run_in_main_runtime_thread_js=g.asm.Vd).apply(null,arguments)},le=g._emscripten_dispatch_to_thread_=function(){return(le=g._emscripten_dispatch_to_thread_=g.asm.Wd).apply(null,arguments)},sc=g.__emscripten_proxy_execute_task_queue=function(){return(sc=g.__emscripten_proxy_execute_task_queue=g.asm.Xd).apply(null,arguments)},ac=g.__emscripten_thread_free_data=function(){return(ac=g.__emscripten_thread_free_data=g.asm.Yd).apply(null,
arguments)},jc=g.__emscripten_thread_exit=function(){return(jc=g.__emscripten_thread_exit=g.asm.Zd).apply(null,arguments)},ic=g._emscripten_stack_set_limits=function(){return(ic=g._emscripten_stack_set_limits=g.asm._d).apply(null,arguments)},fc=g.stackSave=function(){return(fc=g.stackSave=g.asm.$d).apply(null,arguments)},gc=g.stackRestore=function(){return(gc=g.stackRestore=g.asm.ae).apply(null,arguments)},ke=g.stackAlloc=function(){return(ke=g.stackAlloc=g.asm.be).apply(null,arguments)};
g.___cxa_is_pointer_type=function(){return(g.___cxa_is_pointer_type=g.asm.ce).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.de).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.ee).apply(null,arguments)};g.keepRuntimeAlive=function(){return noExitRuntime};g.wasmMemory=qa;g.ExitStatus=db;var sg;Ua=function tg(){sg||ug();sg||(Ua=tg)};
function vg(a){var b=g.__emscripten_proxy_main;a=a||[];a.unshift(ca);var c=a.length,d=ke(4*(c+1)),e=d>>2;a.forEach(f=>{var h=e++,m=xa(f)+1,n=ke(m);wa(f,t,n,m);v[h]=n});v[e]=0;b(c,d)}
function ug(){function a(){if(!sg&&(sg=!0,g.calledRun=!0,!sa)){Ja();k||Qa(Ga);if(g.onRuntimeInitialized)g.onRuntimeInitialized();wg&&vg(b);if(!k){if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Ia.unshift(c)}Qa(Ia)}}}var b=b||ba;if(!(0<Sa))if(k)Ja(),postMessage({cmd:"loaded"});else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ra();Qa(Ea);0<Sa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},
1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var wg=!0;g.noInitialRun&&(wg=!1);ug();
