
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,fa="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.wg&&"string"==typeof process.wg.node,k=g.ENVIRONMENT_IS_PTHREAD||!1,_scriptDir="undefined"!=typeof document&&document.currentScript?document.currentScript.src:void 0;fa&&(_scriptDir=self.location.href);var ka="";
function la(a){return g.locateFile?g.locateFile(a,ka):ka+a}var ma,na;if(ea||fa)fa?ka=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),na=a=>{document.title=a};var oa=g.print||console.log.bind(console),l=g.printErr||console.warn.bind(console);
Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var pa;g.wasmBinary&&(pa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&p("no native wasm support detected");var qa,ra,sa=!1,ta="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ta)return ta.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function va(a,b){return a?ua(q,a,b):""}function wa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var m=a.charCodeAt(++f);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function r(a,b,c){return wa(a,q,b,c)}function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var ya,t,q,za,Aa,v,w,y,B;k&&(ya=g.buffer);var Ba=g.INITIAL_MEMORY||33554432;
if(k)qa=g.wasmMemory,ya=g.buffer;else if(g.wasmMemory)qa=g.wasmMemory;else if(qa=new WebAssembly.Memory({initial:Ba/65536,maximum:Ba/65536,shared:!0}),!(qa.buffer instanceof SharedArrayBuffer))throw l("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),ha&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");qa&&(ya=qa.buffer);Ba=ya.byteLength;var Ca=ya;ya=Ca;g.HEAP8=t=new Int8Array(Ca);g.HEAP16=za=new Int16Array(Ca);g.HEAP32=v=new Int32Array(Ca);g.HEAPU8=q=new Uint8Array(Ca);g.HEAPU16=Aa=new Uint16Array(Ca);g.HEAPU32=w=new Uint32Array(Ca);g.HEAPF32=y=new Float32Array(Ca);g.HEAPF64=B=new Float64Array(Ca);var Da,Ea=[],Fa=[],Ga=[],Ha=[],Ia=[];
function Ja(){k||(g.noFSInit||Ka||(Ka=!0,La(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Ma("stdin",g.stdin):Na("/dev/tty","/dev/stdin"),g.stdout?Ma("stdout",null,g.stdout):Na("/dev/tty","/dev/stdout"),g.stderr?Ma("stderr",null,g.stderr):Na("/dev/tty1","/dev/stderr"),Oa("/dev/stdin",0),Oa("/dev/stdout",1),Oa("/dev/stderr",1)),Pa=!1,Qa(Fa))}function Ra(){var a=g.preRun.shift();Ea.unshift(a)}var Sa=0,Ta=null,Ua=null;
function p(a){if(k)postMessage({cmd:"onAbort",arg:a});else if(g.onAbort)g.onAbort(a);l("Aborted("+a+")");sa=!0;Va()}function Wa(){return Xa.startsWith("data:application/octet-stream;base64,")}var Xa;Xa="chip8pp.wasm";Wa()||(Xa=la(Xa));function Ya(){var a=Xa;try{if(a==Xa&&pa)return new Uint8Array(pa);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function Za(){return pa||!ea&&!fa||"function"!=typeof fetch?Promise.resolve().then(function(){return Ya()}):fetch(Xa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Xa+"'";return a.arrayBuffer()}).catch(function(){return Ya()})}
var C,$a,db={84280:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,84427:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,84661:a=>{"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;a?b.capture={}:b.audio={};b.ie||("undefined"!==typeof AudioContext?b.ie=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ie=new webkitAudioContext),b.ie&&
ab(b.ie));return void 0===b.ie?-1:0},85154:()=>g.SDL2.ie.sampleRate,85222:(a,b,c,d)=>{function e(){}function f(m){void 0!==h.capture.Me&&(clearTimeout(h.capture.Me),h.capture.Me=void 0);h.capture.Ue=h.ie.createMediaStreamSource(m);h.capture.le=h.ie.createScriptProcessor(b,a,1);h.capture.le.onaudioprocess=function(n){void 0!==h&&void 0!==h.capture&&(n.outputBuffer.getChannelData(0).fill(0),h.capture.bf=n.inputBuffer,bb(c,[d]))};h.capture.Ue.connect(h.capture.le);h.capture.le.connect(h.ie.destination);
h.capture.stream=m}var h=g.SDL2;h.capture.Ze=h.ie.createBuffer(a,b,h.ie.sampleRate);h.capture.Ze.getChannelData(0).fill(0);h.capture.Me=setTimeout(function(){h.capture.bf=h.capture.Ze;bb(c,[d])},b/h.ie.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},86874:(a,b,c,d)=>{var e=g.SDL2;e.audio.le=
e.ie.createScriptProcessor(b,0,a);e.audio.le.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.qf=f.outputBuffer,bb(c,[d]))};e.audio.le.connect(e.ie.destination)},87284:(a,b)=>{for(var c=g.SDL2,d=c.capture.bf.numberOfChannels,e=0;e<d;++e){var f=c.capture.bf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var h=0;h<b;++h)cb(a+4*h,f[h]);else for(h=0;h<b;++h)cb(a+4*(h*d+e),
f[h])}},87889:(a,b)=>{for(var c=g.SDL2,d=c.audio.qf.numberOfChannels,e=0;e<d;++e){var f=c.audio.qf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)f[h]=y[a+(h*d+e<<2)>>2]}},88369:a=>{var b=g.SDL2;if(a){void 0!==b.capture.Me&&clearTimeout(b.capture.Me);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=
void 0}void 0!==b.capture.le&&(b.capture.le.onaudioprocess=function(){},b.capture.le.disconnect(),b.capture.le=void 0);void 0!==b.capture.Ue&&(b.capture.Ue.disconnect(),b.capture.Ue=void 0);void 0!==b.capture.Ze&&(b.capture.Ze=void 0);b.capture=void 0}else void 0!=b.audio.le&&(b.audio.le.disconnect(),b.audio.le=void 0),b.audio=void 0;void 0!==b.ie&&void 0===b.audio&&void 0===b.capture&&(b.ie.close(),b.ie=void 0)},89541:(a,b,c)=>{g.SDL2||(g.SDL2={});var d=g.SDL2;d.Rf!==g.canvas&&(d.re=g.createContext(g.canvas,
!1,!0),d.Rf=g.canvas);if(d.w!==a||d.bg!==b||d.eg!==d.re)d.image=d.re.createImageData(a,b),d.w=a,d.bg=b,d.eg=d.re;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=v[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Uf!==a&&(d.Tf=new Int32Array(a.buffer),d.Vf=new Uint8Array(a.buffer),d.Uf=a),a=d.Tf,c=a.length,a.set(v.subarray(b,b+c)),a=d.Vf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,
b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.re.putImageData(d.image,0,0)},91010:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var h=f.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var u=v[e];b[m]=u&255;b[m+1]=u>>8&255;b[m+2]=u>>16&255;b[m+3]=u>>24&255;e++;m+=
4}else b=new Int32Array(b.buffer),n=b.length,b.set(v.subarray(e,e+n));h.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);r(c,d,c.length+1);return d},91999:a=>{g.canvas&&(g.canvas.style.cursor=va(a))},92082:()=>{g.canvas&&(g.canvas.style.cursor="none")},92151:()=>window.innerWidth,92181:()=>window.innerHeight};function eb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function fb(a){(a=E.ye[a])||p();E.If(a)}function gb(a){var b=E.ag();if(!b)return 6;E.Le.push(b);E.ye[a.xe]=b;b.xe=a.xe;var c={cmd:"run",start_routine:a.rg,arg:a.lf,pthread_ptr:a.xe};b.Ke=()=>{c.time=performance.now();b.postMessage(c,a.tg)};b.loaded&&(b.Ke(),delete b.Ke);return 0}
var hb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},ib=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=hb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},jb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},kb=a=>
{if("/"===a)return"/";a=ib(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function lb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>p("randomDevice")}
function mb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=hb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var nb=[];function ob(a,b){nb[a]={input:[],ke:[],He:b};pb(a,qb)}
var qb={open:function(a){var b=nb[a.node.Ye];if(!b)throw new F(43);a.he=b;a.seekable=!1},close:function(a){a.he.He.Qe(a.he)},Qe:function(a){a.he.He.Qe(a.he)},read:function(a,b,c,d){if(!a.he||!a.he.He.vf)throw new F(60);for(var e=0,f=0;f<d;f++){try{var h=a.he.He.vf(a.he)}catch(m){throw new F(29);}if(void 0===h&&0===e)throw new F(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.he||!a.he.He.df)throw new F(60);try{for(var e=0;e<d;e++)a.he.He.df(a.he,
b[c+e])}catch(f){throw new F(29);}d&&(a.node.timestamp=Date.now());return e}},rb={vf:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;var c=Array(xa(b)+1);b=wa(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},df:function(a,b){null===b||10===b?(oa(ua(a.ke,0)),a.ke=[]):0!=b&&a.ke.push(b)},Qe:function(a){a.ke&&
0<a.ke.length&&(oa(ua(a.ke,0)),a.ke=[])}},sb={df:function(a,b){null===b||10===b?(l(ua(a.ke,0)),a.ke=[]):0!=b&&a.ke.push(b)},Qe:function(a){a.ke&&0<a.ke.length&&(l(ua(a.ke,0)),a.ke=[])}},G={te:null,we:function(){return G.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);G.te||(G.te={dir:{node:{Be:G.ee.Be,ue:G.ee.ue,Ie:G.ee.Ie,Ve:G.ee.Ve,Hf:G.ee.Hf,Pf:G.ee.Pf,Jf:G.ee.Jf,Gf:G.ee.Gf,$e:G.ee.$e},stream:{Fe:G.fe.Fe}},file:{node:{Be:G.ee.Be,
ue:G.ee.ue},stream:{Fe:G.fe.Fe,read:G.fe.read,write:G.fe.write,jf:G.fe.jf,zf:G.fe.zf,Bf:G.fe.Bf}},link:{node:{Be:G.ee.Be,ue:G.ee.ue,Je:G.ee.Je},stream:{}},nf:{node:{Be:G.ee.Be,ue:G.ee.ue},stream:tb}});c=ub(a,b,c,d);16384===(c.mode&61440)?(c.ee=G.te.dir.node,c.fe=G.te.dir.stream,c.de={}):32768===(c.mode&61440)?(c.ee=G.te.file.node,c.fe=G.te.file.stream,c.ge=0,c.de=null):40960===(c.mode&61440)?(c.ee=G.te.link.node,c.fe=G.te.link.stream):8192===(c.mode&61440)&&(c.ee=G.te.nf.node,c.fe=G.te.nf.stream);
c.timestamp=Date.now();a&&(a.de[b]=c,a.timestamp=c.timestamp);return c},Jg:function(a){return a.de?a.de.subarray?a.de.subarray(0,a.ge):new Uint8Array(a.de):new Uint8Array(0)},sf:function(a,b){var c=a.de?a.de.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.de,a.de=new Uint8Array(b),0<a.ge&&a.de.set(c.subarray(0,a.ge),0))},og:function(a,b){if(a.ge!=b)if(0==b)a.de=null,a.ge=0;else{var c=a.de;a.de=new Uint8Array(b);c&&a.de.set(c.subarray(0,Math.min(b,a.ge)));a.ge=
b}},ee:{Be:function(a){var b={};b.Eg=8192===(a.mode&61440)?a.id:1;b.Lg=a.id;b.mode=a.mode;b.Qg=1;b.uid=0;b.Kg=0;b.Ye=a.Ye;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ge:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.zg=new Date(a.timestamp);b.Og=new Date(a.timestamp);b.Dg=new Date(a.timestamp);b.Qf=4096;b.Ag=Math.ceil(b.size/b.Qf);return b},ue:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&G.og(a,b.size)},
Ie:function(){throw vb[44];},Ve:function(a,b,c,d){return G.createNode(a,b,c,d)},Hf:function(a,b,c){if(16384===(a.mode&61440)){try{var d=wb(b,c)}catch(f){}if(d)for(var e in d.de)throw new F(55);}delete a.parent.de[a.name];a.parent.timestamp=Date.now();a.name=c;b.de[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Pf:function(a,b){delete a.de[b];a.timestamp=Date.now()},Jf:function(a,b){var c=wb(a,b),d;for(d in c.de)throw new F(55);delete a.de[b];a.timestamp=Date.now()},Gf:function(a){var b=[".",".."],
c;for(c in a.de)a.de.hasOwnProperty(c)&&b.push(c);return b},$e:function(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},Je:function(a){if(40960!==(a.mode&61440))throw new F(28);return a.link}},fe:{read:function(a,b,c,d,e){var f=a.node.de;if(e>=a.node.ge)return 0;a=Math.min(a.node.ge-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.de||a.de.subarray)){if(f)return a.de=
b.subarray(c,c+d),a.ge=d;if(0===a.ge&&0===e)return a.de=b.slice(c,c+d),a.ge=d;if(e+d<=a.ge)return a.de.set(b.subarray(c,c+d),e),d}G.sf(a,e+d);if(a.de.subarray&&b.subarray)a.de.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.de[e+f]=b[c+f];a.ge=Math.max(a.ge,e+d);return d},Fe:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ge);if(0>b)throw new F(28);return b},jf:function(a,b,c){G.sf(a.node,b+c);a.node.ge=Math.max(a.node.ge,b+c)},zf:function(a,b,c,d,e){if(32768!==
(a.node.mode&61440))throw new F(43);a=a.node.de;if(e&2||a.buffer!==ya){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;p();b=void 0;if(!b)throw new F(48);t.set(a,b)}else c=!1,b=a.byteOffset;return{Tg:b,yg:c}},Bf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(43);if(e&2)return 0;G.fe.write(a,b,0,d,c,!1);return 0}}},xb=null,yb={},zb=[],Ab=1,Bb=null,Pa=!0,F=null,vb={},Db=(a,b={})=>{a=mb("/",a);if(!a)return{path:"",node:null};b=Object.assign({uf:!0,
ef:0},b);if(8<b.ef)throw new F(32);a=hb(a.split("/").filter(h=>!!h),!1);for(var c=xb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=wb(c,a[e]);d=ib(d+"/"+a[e]);c.We&&(!f||f&&b.uf)&&(c=c.We.root);if(!f||b.tf)for(f=0;40960===(c.mode&61440);)if(c=Cb(d),d=mb(jb(d),c),c=Db(d,{ef:b.ef+1}).node,40<f++)throw new F(32);}return{path:d,node:c}},Eb=a=>{for(var b;;){if(a===a.parent)return a=a.we.Af,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Fb=(a,b)=>{for(var c=
0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Bb.length},wb=(a,b)=>{var c;if(c=(c=Gb(a,"x"))?c:a.ee.Ie?0:2)throw new F(c,a);for(c=Bb[Fb(a.id,b)];c;c=c.lg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ee.Ie(a,b)},ub=(a,b,c,d)=>{a=new Hb(a,b,c,d);b=Fb(a.parent.id,a.name);a.lg=Bb[b];return Bb[b]=a},Ib={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Jb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Gb=(a,b)=>{if(Pa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&
!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Kb=(a,b)=>{try{return wb(a,b),20}catch(c){}return Gb(a,"wx")},Lb=(a=0)=>{for(;4096>=a;a++)if(!zb[a])return a;throw new F(33);},Nb=(a,b)=>{Mb||(Mb=function(){this.se={}},Mb.prototype={},Object.defineProperties(Mb.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.se.flags},set:function(c){this.se.flags=c}},position:{get:function(){return this.se.position},set:function(c){this.se.position=
c}}}));a=Object.assign(new Mb,a);b=Lb(b);a.Ae=b;return zb[b]=a},tb={open:a=>{a.fe=yb[a.node.Ye].fe;a.fe.open&&a.fe.open(a)},Fe:()=>{throw new F(70);}},pb=(a,b)=>{yb[a]={fe:b}},Ob=(a,b)=>{var c="/"===b,d=!b;if(c&&xb)throw new F(10);if(!c&&!d){var e=Db(b,{uf:!1});b=e.path;e=e.node;if(e.We)throw new F(10);if(16384!==(e.mode&61440))throw new F(54);}b={type:a,Sg:{},Af:b,kg:[]};a=a.we(b);a.we=b;b.root=a;c?xb=a:e&&(e.We=b,e.we&&e.we.kg.push(b))},H=(a,b,c)=>{var d=Db(a,{parent:!0}).node;a=kb(a);if(!a||"."===
a||".."===a)throw new F(28);var e=Kb(d,a);if(e)throw new F(e);if(!d.ee.Ve)throw new F(63);return d.ee.Ve(d,a,b,c)},Pb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);H(a,b|8192,c)},Na=(a,b)=>{if(!mb(a))throw new F(44);var c=Db(b,{parent:!0}).node;if(!c)throw new F(44);b=kb(b);var d=Kb(c,b);if(d)throw new F(d);if(!c.ee.$e)throw new F(63);c.ee.$e(c,b,a)},Cb=a=>{a=Db(a).node;if(!a)throw new F(44);if(!a.ee.Je)throw new F(28);return mb(Eb(a.parent),a.ee.Je(a))},Oa=(a,b,c)=>{if(""===a)throw new F(44);if("string"==
typeof b){var d=Ib[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=ib(a);try{e=Db(a,{tf:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new F(20);}else e=H(a,c,0),d=!0;if(!e)throw new F(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new F(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Jb(b)||b&512)?31:Gb(e,Jb(b)):
44))throw new F(c);if(b&512&&!d){c=e;c="string"==typeof c?Db(c,{tf:!0}).node:c;if(!c.ee.ue)throw new F(63);if(16384===(c.mode&61440))throw new F(31);if(32768!==(c.mode&61440))throw new F(28);if(d=Gb(c,"w"))throw new F(d);c.ee.ue(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Nb({node:e,path:Eb(e),flags:b,seekable:!0,position:0,fe:e.fe,ug:[],error:!1});e.fe.open&&e.fe.open(e);!g.logReadFiles||b&1||(Qb||(Qb={}),a in Qb||(Qb[a]=1));return e},Rb=(a,b,c)=>{if(null===a.Ae)throw new F(8);if(!a.seekable||
!a.fe.Fe)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.fe.Fe(a,b,c);a.ug=[]},La=()=>{F||(F=function(a,b){this.node=b;this.pg=function(c){this.Ee=c};this.pg(a);this.message="FS error"},F.prototype=Error(),F.prototype.constructor=F,[44].forEach(a=>{vb[a]=new F(a);vb[a].stack="<generic error, no stack>"}))},Ka,Sb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ma=(a,b,c)=>{a=ib("/dev/"+a);var d=Sb(!!b,!!c);Tb||(Tb=64);var e=Tb++<<8|0;pb(e,{open:f=>{f.seekable=!1},close:()=>{c&&c.buffer&&
c.buffer.length&&c(10)},read:(f,h,m,n)=>{for(var u=0,x=0;x<n;x++){try{var z=b()}catch(A){throw new F(29);}if(void 0===z&&0===u)throw new F(6);if(null===z||void 0===z)break;u++;h[m+x]=z}u&&(f.node.timestamp=Date.now());return u},write:(f,h,m,n)=>{for(var u=0;u<n;u++)try{c(h[m+u])}catch(x){throw new F(29);}n&&(f.node.timestamp=Date.now());return u}});Pb(a,d,e)},Tb,Ub={},Mb,Qb,Vb=void 0;function Wb(){Vb+=4;return v[Vb-4>>2]}function Xb(a){a=zb[a];if(!a)throw new F(8);return a}
function Yb(a){if(k)return I(1,1,a);if(!noExitRuntime){E.sg();if(g.onExit)g.onExit(a);sa=!0}da(a,new eb(a))}function Zb(a,b){if(!b&&k)throw $b(a),"unwind";Yb(a)}function ac(a){a instanceof eb||"unwind"==a||da(1,a)}
var E={ze:[],Le:[],Mf:[],ye:{},fg:function(){k?E.ig():E.hg()},hg:function(){for(var a=4;a--;)E.kf()},ig:function(){E.receiveObjectTransfer=E.ng;E.threadInitTLS=E.Lf;E.setExitStatus=E.Kf;noExitRuntime=!1},Kf:function(){},sg:function(){for(var a of Object.values(E.ye))E.If(a);for(a of E.ze)a.terminate();E.ze=[]},If:function(a){var b=a.xe;delete E.ye[b];E.ze.push(a);E.Le.splice(E.Le.indexOf(a),1);a.xe=0;bc(b)},ng:function(){},Lf:function(){E.Mf.forEach(a=>a())},xf:function(a,b){a.onmessage=c=>{c=c.data;
var d=c.cmd;a.xe&&(E.rf=a.xe);if(c.targetThread&&c.targetThread!=cc()){var e=E.ye[c.Ug];e?e.postMessage(c,c.transferList):l('Internal error! Worker sent a message "'+d+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===d)dc(c.queue);else if("spawnThread"===d)gb(c);else if("cleanupThread"===d)fb(c.thread);else if("killThread"===d)c=c.thread,d=E.ye[c],delete E.ye[c],d.terminate(),bc(c),E.Le.splice(E.Le.indexOf(d),1),d.xe=0;else if("cancelThread"===
d)E.ye[c.thread].postMessage({cmd:"cancel"});else if("loaded"===d)a.loaded=!0,b&&b(a),a.Ke&&(a.Ke(),delete a.Ke);else if("print"===d)oa("Thread "+c.threadId+": "+c.text);else if("printErr"===d)l("Thread "+c.threadId+": "+c.text);else if("alert"===d)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===c.target)a.postMessage(c);else if("onAbort"===d){if(g.onAbort)g.onAbort(c.arg)}else d&&l("worker sent an unknown command "+d);E.rf=void 0};a.onerror=c=>{l("worker sent an error! "+c.filename+
":"+c.lineno+": "+c.message);throw c;};a.postMessage({cmd:"load",urlOrBlob:g.mainScriptUrlOrBlob||_scriptDir,wasmMemory:qa,wasmModule:ra})},kf:function(){var a=la("chip8pp.worker.js");E.ze.push(new Worker(a))},ag:function(){0==E.ze.length&&(E.kf(),E.xf(E.ze[0]));return E.ze.pop()}};g.PThread=E;function ec(a,b,c){a.addEventListener(b,c,{once:!0})}
function ab(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&ec(d,c,()=>{"suspended"===a.state&&a.resume()})})})}function Qa(a){for(;0<a.length;)a.shift()(g)}function fc(a){var b=gc();a=a();hc(b);return a}var ic=[];function J(a){var b=ic[a];b||(a>=ic.length&&(ic.length=a+1),ic[a]=b=Da.get(a));return b}
function bb(a,b){if("vi".includes("j")){var c=g.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else J(a).apply(null,b)}g.establishStackSpace=function(){var a=cc(),b=v[a+44>>2];jc(b,b-v[a+48>>2]);hc(b)};function $b(a){if(k)return I(2,0,a);try{Zb(a)}catch(b){ac(b)}}g.invokeEntryPoint=function(a,b){a=J(a)(b);noExitRuntime?E.Kf(a):kc(a)};
function cb(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":t[a>>0]=b;break;case "i8":t[a>>0]=b;break;case "i16":za[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":$a=[b>>>0,(C=b,1<=+Math.abs(C)?0<C?(Math.min(+Math.floor(C/4294967296),4294967295)|0)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];v[a>>2]=$a[0];v[a+4>>2]=$a[1];break;case "float":y[a>>2]=b;break;case "double":B[a>>3]=b;break;case "*":w[a>>2]=b;break;default:p("invalid type for setValue: "+c)}}
function lc(a,b,c,d){return k?I(3,1,a,b,c,d):mc(a,b,c,d)}function mc(a,b,c,d){if("undefined"==typeof SharedArrayBuffer)return l("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(k&&0===e.length)return lc(a,b,c,d);a={rg:c,xe:a,lf:d,tg:e};return k?(a.Bg="spawnThread",postMessage(a,e),0):gb(a)}
function nc(a,b,c){if(k)return I(4,1,a,b,c);Vb=c;try{var d=Xb(a);switch(b){case 0:var e=Wb();return 0>e?-28:Nb(d,e).Ae;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Wb(),d.flags|=e,0;case 5:return e=Wb(),za[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return v[oc()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof Ub||!(f instanceof F))throw f;return-f.Ee}}
function pc(a,b,c){if(k)return I(5,1,a,b,c);Vb=c;try{var d=Xb(a);switch(b){case 21509:case 21505:return d.he?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.he?0:-59;case 21519:if(!d.he)return-59;var e=Wb();return v[e>>2]=0;case 21520:return d.he?-28:-59;case 21531:a=e=Wb();if(!d.fe.jg)throw new F(59);return d.fe.jg(d,b,a);case 21523:return d.he?0:-59;case 21524:return d.he?0:-59;default:return-28}}catch(f){if("undefined"==typeof Ub||!(f instanceof F))throw f;return-f.Ee}}
function qc(a,b,c,d){if(k)return I(6,1,a,b,c,d);Vb=d;try{b=va(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Xb(a).path;if(0==e.length)throw new F(44);b=ib(f+"/"+e)}var h=d?Wb():0;return Oa(b,c,h).Ae}catch(m){if("undefined"==typeof Ub||!(m instanceof F))throw m;return-m.Ee}}function dc(a){Atomics.store(v,a>>2,1);cc()&&rc(a);Atomics.compareExchange(v,a>>2,1,0)}g.executeNotifiedProxyingQueue=dc;
function sc(a,b){tc=a;uc=b;if(vc)if(wc||(wc=!0),0==a)xc=function(){var d=Math.max(0,yc+b-zc())|0;setTimeout(Ac,d)};else if(1==a)xc=function(){Bc(Ac)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);fa?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}xc=function(){setImmediate(Ac)}}}var zc;zc=k?()=>performance.now()-g.__performance_now_clock_drift:()=>performance.now();
function Cc(a,b,c,d,e){!vc||p("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");vc=a;Dc=d;var f=Ec;wc=!1;Ac=function(){if(!sa)if(0<Fc.length){var h=Date.now(),m=Fc.shift();m.Hg(m.lf);if(Gc){var n=Gc,u=0==n%1?n-1:Math.floor(n);Gc=m.Cg?u:(8*n+(u+.5))/9}oa('main loop blocker "'+m.name+'" took '+(Date.now()-h)+" ms");g.setStatus&&(h=g.statusMessage||"Please wait...",
m=Gc,n=Hc.Fg,m?m<n?g.setStatus(h+" ("+(n-m)+"/"+n+")"):g.setStatus(h):g.setStatus(""));f<Ec||setTimeout(Ac,0)}else f<Ec||(Ic=Ic+1|0,1==tc&&1<uc&&0!=Ic%uc?xc():(0==tc&&(yc=zc()),sa||g.preMainLoop&&!1===g.preMainLoop()||(Jc(a),g.postMainLoop&&g.postMainLoop()),f<Ec||("object"==typeof SDL&&SDL.audio&&SDL.audio.mg&&SDL.audio.mg(),xc())))};e||(b&&0<b?sc(0,1E3/b):sc(1,1),xc());if(c)throw"unwind";}function Jc(a){if(!sa)try{a()}catch(b){ac(b)}}function Kc(a){setTimeout(function(){Jc(a)},1E4)}
function Lc(a){Mc||(Mc={});Mc[a]||(Mc[a]=1,l(a))}var Mc,wc=!1,xc=null,Ec=0,vc=null,Dc=0,tc=0,uc=0,Ic=0,Fc=[],Hc={},yc,Ac,Gc,Nc=!1,Oc=!1,Pc=[];
function Qc(){function a(){Oc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Rc){Rc=!0;try{Sc=!0}catch(c){Sc=!1,l("warning: no blob constructor, cannot create blobs with mimetypes")}Tc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Sc?null:l("warning: no BlobBuilder");Uc="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Cf||"undefined"!=typeof Uc||(l("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Cf=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Cf&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(Sc)try{h=new Blob([c],{type:Vc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Vc(d)}))}catch(u){Lc("Blob constructor present but fails: "+
u+"; falling back to blob builder")}h||(h=new Tc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=Uc.createObjectURL(h),n=new Image;n.onload=()=>{n.complete||p("Image "+d+" could not be decoded");var u=document.createElement("canvas");u.width=n.width;u.height=n.height;u.getContext("2d").drawImage(n,0,0);Uc.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{oa("Image "+m+" could not be decoded");f&&f()};n.src=m}});g.preloadPlugins.push({canHandle:function(c){return!g.Rg&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,f){function h(){n||(n=!0,e&&e(c))}function m(){n||(n=!0,new Audio,f&&f())}var n=!1;if(Sc){try{var u=new Blob([c],{type:Vc(d)})}catch(z){return m()}u=Uc.createObjectURL(u);var x=new Audio;x.addEventListener("canplaythrough",()=>h(x),!1);x.onerror=function(){if(!n){l("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var z="",A=0,K=0,M=0;M<c.length;M++)for(A=A<<8|c[M],K+=8;6<=K;){var ia=A>>K-6&63;K-=6;z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[ia]}2==
K?(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(A&3)<<4],z+="=="):4==K&&(z+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(A&15)<<2],z+="=");x.src="data:audio/x-"+d.substr(-3)+";base64,"+z;h(x)}};x.src=u;Kc(function(){h(x)})}else return m()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!Oc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Wc(a,b,c,d){if(b&&g.re&&a==g.canvas)return g.re;var e;if(b){var f={antialias:!1,alpha:!1,yf:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!=typeof Xc&&(e=Yc(a,f)))var m=L[e].ne}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof N||p("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.re=m,b&&Zc(e),g.vg=b,Pc.forEach(function(n){n()}),Qc());return m}var $c=!1,ad=void 0,bd=void 0;
function cd(a,b){function c(){Nc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=dd,ad&&d.requestPointerLock(),Nc=!0,bd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=w[SDL.screen>>2]|8388608),ed(g.canvas),fd()):ed(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),bd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=w[SDL.screen>>2]&
-8388609),ed(g.canvas),fd()):ed(d));if(g.onFullScreen)g.onFullScreen(Nc);if(g.onFullscreen)g.onFullscreen(Nc)}ad=a;bd=b;"undefined"==typeof ad&&(ad=!0);"undefined"==typeof bd&&(bd=!1);var d=g.canvas;$c||($c=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function dd(){if(!Nc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var gd=0;function Bc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===gd)gd=b+1E3/60;else for(;b+2>=gd;)gd+=1E3/60;setTimeout(a,Math.max(gd-b,0))}}
function Vc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var hd=[];function fd(){var a=g.canvas;hd.forEach(function(b){b(a.width,a.height)})}
function ed(a,b,c){b&&c?(a.xg=b,a.dg=c):(b=a.xg,c=a.dg);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}bd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Rc,Sc,Tc,Uc,O=12288,jd=!1,kd=0,ld=0,md=0,P={alpha:!1,depth:!1,stencil:!1,antialias:!1},nd={},od;function pd(a){if(k)return I(7,1,a);if(12448==a)return O=12288,1;O=12300;return 0}
function qd(a,b,c,d,e){if(k)c=I(8,1,a,b,c,d,e);else if(62E3!=a)O=12296,c=0;else{if(b)for(;;){a=v[b>>2];if(12321==a)P.alpha=0<v[b+4>>2];else if(12325==a)P.depth=0<v[b+4>>2];else if(12326==a)P.stencil=0<v[b+4>>2];else if(12337==a)a=v[b+4>>2],P.antialias=0<a;else if(12338==a)a=v[b+4>>2],P.antialias=1==a;else if(12544==a)P.Mg=12547!=v[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(v[e>>2]=1),c&&0<d&&(v[c>>2]=62002),O=12288,c=1):(O=12300,c=0)}return c}
function rd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function sd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function td(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var ud=1,vd=[],Q=[],wd=[],xd=[],yd=[],R=[],zd=[],L={},S=[],Ad={},Bd=4;
function T(a){Cd||(Cd=a)}function Dd(a){for(var b=ud++,c=a.length;c<b;c++)a[c]=null;return b}function Yc(a,b){a.se||(a.se=a.getContext,a.getContext=function(d,e){e=a.se(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Ed(c,b):0}function Ed(a,b){var c=D(8);v[c+4>>2]=cc();var d={cg:c,attributes:b,version:b.yf,ne:a};a.canvas&&(a.canvas.ve=d);L[c]=d;("undefined"==typeof b.Yf||b.Yf)&&Fd(d);return c}function Zc(a){Gd=L[a];g.re=N=Gd&&Gd.ne}
function Fd(a){a||(a=Gd);if(!a.gg){a.gg=!0;var b=a.ne;rd(b);sd(b);td(b);b.pe=b.getExtension("EXT_disjoint_timer_query");b.Pg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Xc={},Cd,Gd;
function Hd(a,b,c,d){if(k)return I(9,1,a,b,c,d);if(62E3!=a)return O=12296,0;for(a=1;;){b=v[d>>2];if(12440==b)a=v[d+4>>2];else if(12344==b)break;else return O=12292,0;d+=8}if(2!=a)return O=12293,0;P.yf=a-1;P.Ng=0;od=Yc(g.canvas,P);if(0!=od)return O=12288,Zc(od),g.vg=!0,Pc.forEach(function(e){e()}),Zc(null),62004;O=12297;return 0}function Id(a,b,c,d){if(k)return I(10,1,a,b,c,d);if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;O=12288;return 62006}
function Jd(a,b){if(k)return I(11,1,a,b);if(62E3!=a)return O=12296,0;if(62004!=b)return O=12294,0;a=od;Gd===L[a]&&(Gd=null);if("object"==typeof Kd)for(var c=L[a].ne.canvas,d=0;d<Ld.length;++d)Ld[d].target!=c||Md(d--);L[a]&&L[a].ne.canvas&&(L[a].ne.canvas.ve=void 0);Nd(L[a].cg);L[a]=null;O=12288;kd==b&&(kd=0);return 1}function Od(a,b){if(k)return I(12,1,a,b);if(62E3!=a)return O=12296,0;if(62006!=b)return O=12301,1;ld==b&&(ld=0);md==b&&(md=0);O=12288;return 1}
function Pd(a,b,c,d){if(k)return I(13,1,a,b,c,d);if(62E3!=a)return O=12296,0;if(62002!=b)return O=12293,0;if(!d)return O=12300,0;O=12288;switch(c){case 12320:return v[d>>2]=P.alpha?32:24,1;case 12321:return v[d>>2]=P.alpha?8:0,1;case 12322:return v[d>>2]=8,1;case 12323:return v[d>>2]=8,1;case 12324:return v[d>>2]=8,1;case 12325:return v[d>>2]=P.depth?24:0,1;case 12326:return v[d>>2]=P.stencil?8:0,1;case 12327:return v[d>>2]=12344,1;case 12328:return v[d>>2]=62002,1;case 12329:return v[d>>2]=0,1;case 12330:return v[d>>
2]=4096,1;case 12331:return v[d>>2]=16777216,1;case 12332:return v[d>>2]=4096,1;case 12333:return v[d>>2]=0,1;case 12334:return v[d>>2]=0,1;case 12335:return v[d>>2]=12344,1;case 12337:return v[d>>2]=P.antialias?4:0,1;case 12338:return v[d>>2]=P.antialias?1:0,1;case 12339:return v[d>>2]=4,1;case 12340:return v[d>>2]=12344,1;case 12341:case 12342:case 12343:return v[d>>2]=-1,1;case 12345:case 12346:return v[d>>2]=0,1;case 12347:return v[d>>2]=0,1;case 12348:return v[d>>2]=1;case 12349:case 12350:return v[d>>
2]=0,1;case 12351:return v[d>>2]=12430,1;case 12352:return v[d>>2]=4,1;case 12354:return v[d>>2]=0,1;default:return O=12292,0}}function Qd(a){if(k)return I(14,1,a);O=12288;return 62E3}function Rd(){return k?I(15,1):O}function Sd(a,b,c){if(k)return I(16,1,a,b,c);if(62E3!=a)return O=12296,0;b&&(v[b>>2]=1);c&&(v[c>>2]=4);jd=!0;O=12288;return 1}
function Td(a,b,c,d){if(k)return I(17,1,a,b,c,d);if(62E3!=a)return O=12296,0;if(0!=d&&62004!=d)return O=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return O=12301,0;Zc(d?od:null);kd=d;md=b;ld=c;O=12288;return 1}function Ud(a){var b=xa(a)+1,c=D(b);c&&wa(a,t,c,b);return c}
function Vd(a,b){if(k)return I(18,1,a,b);if(62E3!=a)return O=12296,0;O=12288;if(nd[b])return nd[b];switch(b){case 12371:a=Ud("Emscripten");break;case 12372:a=Ud("1.4 Emscripten EGL");break;case 12373:a=Ud("");break;case 12429:a=Ud("OpenGL_ES");break;default:return O=12300,0}return nd[b]=a}function Wd(){if(k)return I(19,1);if(jd)if(g.re)if(g.re.isContextLost())O=12302;else return O=12288,1;else O=12290;else O=12289;return 0}
function Xd(a,b){if(k)return I(20,1,a,b);if(62E3!=a)return O=12296,0;0==b?sc(0,0):sc(1,b);O=12288;return 1}function Yd(a){if(k)return I(21,1,a);if(62E3!=a)return O=12296,0;md=ld=kd=0;jd=!1;O=12288;return 1}function Zd(){if(k)return I(22,1);O=12288;return 1}function $d(a){if(k)return I(23,1,a);O=12288;return 1}var ae=[];function be(a,b){ae.length=0;var c;for(b>>=2;c=q[a++];)b+=105!=c&b,ae.push(105==c?v[b]:B[b++>>1]),++b;return ae}var ce=0;
function de(){for(var a=Ld.length-1;0<=a;--a)Md(a);Ld=[];U=[]}var U=[];function ee(a,b,c){function d(h,m){if(h.length!=m.length)return!1;for(var n in h)if(h[n]!=m[n])return!1;return!0}for(var e in U){var f=U[e];if(f.gf==a&&d(f.mf,c))return}U.push({gf:a,Ef:b,mf:c});U.sort(function(h,m){return h.Ef<m.Ef})}function fe(a){for(var b=0;b<U.length;++b)U[b].gf==a&&(U.splice(b,1),--b)}function ge(){if(ce&&he.De)for(var a=0;a<U.length;++a){var b=U[a];U.splice(a,1);--a;b.gf.apply(null,b.mf)}}var Ld=[];
function Md(a){var b=Ld[a];b.target.removeEventListener(b.je,b.Zf,b.me);Ld.splice(a,1)}function V(a){function b(d){++ce;he=a;ge();a.qe(d);ge();--ce}if(a.oe)a.Zf=b,a.target.addEventListener(a.je,b,a.me),Ld.push(a),ie||(Ha.push(de),ie=!0);else for(var c=0;c<Ld.length;++c)Ld[c].target==a.target&&Ld[c].je==a.je&&Md(c--)}function W(a,b,c,d,e){fc(function(){var f=je(12);v[f>>2]=c;v[f+4>>2]=d;v[f+8>>2]=e;ke(a,637534208,b,d,f)})}
function le(a){switch(a){case 1:return 0;case 2:return E.rf;default:return a}}function me(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function ne(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var Kd={},ie,he,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae={},Be=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function X(a){a=2<a?va(a):a;return Be[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Ce(a,b,c){a=X(a);if(!a||a.pf)return-4;v[b>>2]=a.width;v[c>>2]=a.height;return 0}function De(a,b,c){return k?I(25,1,a,b,c):Ce(a,b,c)}function Ee(a){return fc(function(){var b=je(8),c=b+4,d=je(a.id.length+1);r(a.id,d,a.id.length+1);X(d)?Ce(d,b,c):De(d,b,c);return[v[b>>2],v[c>>2]]})}
function Fe(a,b,c){a=X(a);if(!a||a.pf)return-4;var d=!1;a.ve&&a.ve.ne&&(d=a.ve.ne.getParameter(2978),d=0===d[0]&&0===d[1]&&d[2]===a.width&&d[3]===a.height);a.width=b;a.height=c;d&&a.ve.ne.viewport(0,0,b,c);return 0}function Ge(a,b,c){return k?I(26,1,a,b,c):Fe(a,b,c)}function He(a,b,c){return X(a)?Fe(a,b,c):Ge(a,b,c)}function Ie(a,b,c){a.pf?fc(function(){var d=je(a.id.length+1);r(a.id,d,a.id.length+1);He(d,b,c)}):(a.width=b,a.height=c)}
function Je(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Ie(a,d,e),a.style.width=f,a.style.height=h,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=u,a.style.paddingRight=x,a.style.paddingTop=z,a.style.paddingBottom=A,a.style.marginLeft=K,a.style.marginRight=
M,a.style.marginTop=ia,a.style.marginBottom=ja,document.body.style.margin=hg,document.documentElement.style.overflow=ig,document.body.scroll=jg,a.style.Ce=kg,a.ve&&a.ve.ne.viewport(0,0,d,e),Ae.Ge&&(Ae.Oe?W(Ae.Oe,Ae.Ge,37,0,Ae.Pe):J(Ae.Ge)(37,0,Ae.Pe)))}var c=Ee(a),d=c[0],e=c[1],f=a.style.width,h=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,u=a.style.paddingLeft,x=a.style.paddingRight,z=a.style.paddingTop,A=a.style.paddingBottom,K=a.style.marginLeft,M=a.style.marginRight,
ia=a.style.marginTop,ja=a.style.marginBottom,hg=document.body.style.margin,ig=document.documentElement.style.overflow,jg=document.body.scroll,kg=a.style.Ce;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Ke(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Le(a){return 0>Be.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Me(a,b){if(0!=b.ff||0!=b.af){Je(a);var c=b.qg?innerWidth:screen.width,d=b.qg?innerHeight:screen.height,e=Le(a),f=e.width;e=e.height;var h=Ee(a),m=h[0];h=h[1];3==b.ff?(Ke(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.ff&&(c*h<m*d?(f=h*c/m,Ke(a,(d-f)/2,0),d=f):(f=m*d/h,Ke(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.$f&&(a.style.Ce="optimizeSpeed",
a.style.Ce="-moz-crisp-edges",a.style.Ce="-o-crisp-edges",a.style.Ce="-webkit-optimize-contrast",a.style.Ce="optimize-contrast",a.style.Ce="crisp-edges",a.style.Ce="pixelated");f=2==b.af?devicePixelRatio:1;0!=b.af&&(c=c*f|0,d=d*f|0,Ie(a,c,d),a.ve&&a.ve.ne.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return ne()?-3:-1;Ae=b;b.Ge&&(b.Oe?W(b.Oe,b.Ge,37,0,b.Pe):J(b.Ge)(37,0,b.Pe));return 0}
function Ne(){if(k)return I(24,1);if(!ne())return-1;fe(Me);var a=Be[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0}function Oe(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Xe)a.Xe();else return document.body.requestPointerLock||document.body.Xe?-3:-1;return 0}
function Pe(){if(k)return I(27,1);fe(Oe);if(document.exitPointerLock)document.exitPointerLock();else if(document.se)document.se();else return-1;return 0}function Qe(){return k?I(28,1):devicePixelRatio}function Re(a,b,c){if(k)return I(29,1,a,b,c);a=X(a);if(!a)return-4;a=Le(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0}
function Se(a,b){B[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)B[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)B[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)v[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];v[a+1296>>2]=b.connected;v[a+1300>>2]=b.index;v[a+8>>2]=b.axes.length;v[a+12>>2]=b.buttons.length;r(b.id,a+1304,64);r(b.mapping,a+1368,64)}
function Te(a,b){if(k)return I(30,1,a,b);if(0>a||a>=oe.length)return-5;if(!oe[a])return-7;Se(b,oe[a]);return 0}function Ue(){return k?I(31,1):oe.length}function Ve(a,b){if(k)return I(32,1,a,b);v[a>>2]=screen.width;v[b>>2]=screen.height}var We=[];function Xe(a,b,c,d){for(var e=0;e<a;e++){var f=N[c](),h=f&&Dd(d);f?(f.name=h,d[h]=f):T(1282);v[b+4*e>>2]=h}}function Ye(a,b,c,d,e,f,h,m){b=Q[b];if(a=N[a](b,c))d=m&&r(a.name,m,d),e&&(v[e>>2]=d),f&&(v[f>>2]=a.size),h&&(v[h>>2]=a.type)}
function Ze(a,b){w[a>>2]=b;w[a+4>>2]=(b-w[a>>2])/4294967296}
function $e(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&T(1280);return;case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:T(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;case 4:t[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){T(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:T(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Ze(b,
d);break;case 0:v[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:t[b>>0]=d?1:0}}else T(1281)}function af(a){var b=xa(a)+1,c=D(b);r(a,c,b);return c}function bf(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function cf(a){var b=a.Ne,c=a.Of,d;if(!b)for(a.Ne=b={},a.Nf={},d=0;d<N.getProgramParameter(a,35718);++d){var e=N.getActiveUniform(a,d);var f=e.name;e=e.size;var h=bf(f);h=0<h?f.slice(0,h):f;var m=a.hf;a.hf+=e;c[h]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Nf[m++]=h}}
function Y(a){var b=N.Sf;if(b){var c=b.Ne[a];"number"==typeof c&&(b.Ne[a]=c=N.getUniformLocation(b,b.Nf[a]+(0<c?"["+c+"]":"")));return c}T(1282)}function df(a,b,c,d){if(c)if(a=Q[a],cf(a),a=N.getUniform(a,Y(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else T(1281)}
function ef(a,b,c,d){if(c)if(a=N.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:y[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b])}else T(1281)}
function ff(a,b,c,d,e){a-=5120;a=1==a?q:4==a?v:6==a?y:5==a||28922==a?w:Aa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Bd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var gf=[],hf=[];function I(a,b){var c=arguments.length-2,d=arguments;return fc(()=>{for(var e=je(8*c),f=e>>3,h=0;h<c;h++)B[f+h]=d[2+h];return jf(a,c,e,b)})}var kf=[];
function lf(a,b){if(!ne())return-1;a=X(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?ce&&he.De?Me(a,b):b.Wf?(ee(Me,1,[a,b]),1):-2:-3:-4}function mf(a,b,c){return k?I(33,1,a,b,c):lf(a,{ff:v[c>>2],af:v[c+4>>2],$f:v[c+8>>2],Wf:b,Oe:v[c+20>>2],Ge:v[c+12>>2],Pe:v[c+16>>2]})}function nf(a,b){if(k)return I(34,1,a,b);a=X(a);return a?a.requestPointerLock||a.Xe?ce&&he.De?Oe(a):b?(ee(Oe,2,[a]),1):-2:-1:-4}
function of(){return k?I(35,1):(oe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1}function pf(a,b){var c={target:X(2),je:"beforeunload",oe:b,qe:function(d){d=d||event;var e=J(b)(28,0,a);e&&(e=va(e));if(e)return d.preventDefault(),d.returnValue=e},me:!0};V(c)}function qf(a,b,c){if(k)return I(36,1,a,b,c);if("undefined"==typeof onbeforeunload)return-1;if(1!==c)return-5;pf(a,b);return 0}
function rf(a,b,c,d,e,f,h){h=le(h);pe||(pe=D(256));a={target:X(a),je:f,oe:d,qe:function(m){m=m||event;var n=me(m.target),u=m.target.id?m.target.id:"",x=h?D(256):pe;r(n,x+0,128);r(u,x+128,128);h?W(h,d,e,x,b):J(d)(e,x,b)&&m.preventDefault()},me:c};V(a)}function sf(a,b,c,d,e){if(k)return I(37,1,a,b,c,d,e);rf(a,b,c,d,12,"blur",e);return 0}function tf(a,b,c){if(k)return I(38,1,a,b,c);a=X(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0}
function uf(a,b,c,d,e){if(k)return I(39,1,a,b,c,d,e);rf(a,b,c,d,13,"focus",e);return 0}
function vf(a,b,c,d,e,f){f=le(f);re||(re=D(280));V({target:a,je:e,oe:d,qe:function(h){h=h||event;var m=f?D(280):re,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,u=!!n;v[m>>2]=u;v[m+4>>2]=ne();var x=u?n:qe,z=x&&x.id?x.id:"";r(me(x),m+8,128);r(z,m+136,128);v[m+264>>2]=x?x.clientWidth:0;v[m+268>>2]=x?x.clientHeight:0;v[m+272>>2]=screen.width;v[m+276>>2]=screen.height;u&&(qe=n);f?W(f,d,19,m,b):J(d)(19,m,b)&&h.preventDefault()},
me:c})}function wf(a,b,c,d,e){if(k)return I(40,1,a,b,c,d,e);if(!ne())return-1;a=X(a);if(!a)return-4;vf(a,b,c,d,"fullscreenchange",e);vf(a,b,c,d,"webkitfullscreenchange",e);return 0}function xf(a,b,c,d,e,f){f=le(f);se||(se=D(1432));b={target:X(2),De:!0,je:e,oe:c,qe:function(h){h=h||event;var m=f?D(1432):se;Se(m,h.gamepad);f?W(f,c,d,m,a):J(c)(d,m,a)&&h.preventDefault()},me:b};V(b)}
function yf(a,b,c,d){if(k)return I(41,1,a,b,c,d);if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;xf(a,b,c,26,"gamepadconnected",d);return 0}function zf(a,b,c,d){if(k)return I(42,1,a,b,c,d);if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;xf(a,b,c,27,"gamepaddisconnected",d);return 0}
function Af(a,b,c,d,e,f,h){h=le(h);te||(te=D(176));a={target:X(a),De:!0,je:f,oe:d,qe:function(m){var n=h?D(176):te;B[n>>3]=m.timeStamp;var u=n>>2;v[u+2]=m.location;v[u+3]=m.ctrlKey;v[u+4]=m.shiftKey;v[u+5]=m.altKey;v[u+6]=m.metaKey;v[u+7]=m.repeat;v[u+8]=m.charCode;v[u+9]=m.keyCode;v[u+10]=m.which;r(m.key||"",n+44,32);r(m.code||"",n+76,32);r(m.char||"",n+108,32);r(m.locale||"",n+140,32);h?W(h,d,e,n,b):J(d)(e,n,b)&&m.preventDefault()},me:c};V(a)}
function Bf(a,b,c,d,e){if(k)return I(43,1,a,b,c,d,e);Af(a,b,c,d,2,"keydown",e);return 0}function Cf(a,b,c,d,e){if(k)return I(44,1,a,b,c,d,e);Af(a,b,c,d,1,"keypress",e);return 0}function Df(a,b,c,d,e){if(k)return I(45,1,a,b,c,d,e);Af(a,b,c,d,3,"keyup",e);return 0}
function Ef(a,b,c){B[a>>3]=b.timeStamp;a>>=2;v[a+2]=b.screenX;v[a+3]=b.screenY;v[a+4]=b.clientX;v[a+5]=b.clientY;v[a+6]=b.ctrlKey;v[a+7]=b.shiftKey;v[a+8]=b.altKey;v[a+9]=b.metaKey;za[2*a+20]=b.button;za[2*a+21]=b.buttons;v[a+11]=b.movementX;v[a+12]=b.movementY;c=Le(c);v[a+13]=b.clientX-c.left;v[a+14]=b.clientY-c.top}
function Ff(a,b,c,d,e,f,h){h=le(h);ue||(ue=D(72));a=X(a);V({target:a,De:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,je:f,oe:d,qe:function(m){m=m||event;Ef(ue,m,a);if(h){var n=D(72);Ef(n,m,a);W(h,d,e,n,b)}else J(d)(e,ue,b)&&m.preventDefault()},me:c})}function Gf(a,b,c,d,e){if(k)return I(46,1,a,b,c,d,e);Ff(a,b,c,d,5,"mousedown",e);return 0}function Hf(a,b,c,d,e){if(k)return I(47,1,a,b,c,d,e);Ff(a,b,c,d,33,"mouseenter",e);return 0}
function If(a,b,c,d,e){if(k)return I(48,1,a,b,c,d,e);Ff(a,b,c,d,34,"mouseleave",e);return 0}function Jf(a,b,c,d,e){if(k)return I(49,1,a,b,c,d,e);Ff(a,b,c,d,8,"mousemove",e);return 0}function Kf(a,b,c,d,e){if(k)return I(50,1,a,b,c,d,e);Ff(a,b,c,d,6,"mouseup",e);return 0}
function Lf(a,b,c,d,e,f){f=le(f);ve||(ve=D(260));V({target:a,je:e,oe:d,qe:function(h){h=h||event;var m=f?D(260):ve,n=document.pointerLockElement||document.Xf||document.Ig||document.Gg;v[m>>2]=!!n;var u=n&&n.id?n.id:"";r(me(n),m+4,128);r(u,m+132,128);f?W(f,d,20,m,b):J(d)(20,m,b)&&h.preventDefault()},me:c})}
function Mf(a,b,c,d,e){if(k)return I(51,1,a,b,c,d,e);if(!document||!document.body||!(document.body.requestPointerLock||document.body.se||document.body.Xf||document.body.Xe))return-1;a=X(a);if(!a)return-4;Lf(a,b,c,d,"pointerlockchange",e);Lf(a,b,c,d,"mozpointerlockchange",e);Lf(a,b,c,d,"webkitpointerlockchange",e);Lf(a,b,c,d,"mspointerlockchange",e);return 0}
function Nf(a,b,c,d,e){e=le(e);we||(we=D(36));a=X(a);V({target:a,je:"resize",oe:d,qe:function(f){f=f||event;if(f.target==a){var h=document.body;if(h){var m=e?D(36):we;v[m>>2]=f.detail;v[m+4>>2]=h.clientWidth;v[m+8>>2]=h.clientHeight;v[m+12>>2]=innerWidth;v[m+16>>2]=innerHeight;v[m+20>>2]=outerWidth;v[m+24>>2]=outerHeight;v[m+28>>2]=pageXOffset;v[m+32>>2]=pageYOffset;e?W(e,d,10,m,b):J(d)(10,m,b)&&f.preventDefault()}}},me:c})}
function Of(a,b,c,d,e){if(k)return I(52,1,a,b,c,d,e);Nf(a,b,c,d,e);return 0}
function Pf(a,b,c,d,e,f,h){h=le(h);xe||(xe=D(1696));a=X(a);V({target:a,De:"touchstart"==f||"touchend"==f,je:f,oe:d,qe:function(m){for(var n,u={},x=m.touches,z=0;z<x.length;++z)n=x[z],n.wf=n.Df=0,u[n.identifier]=n;for(z=0;z<m.changedTouches.length;++z)n=m.changedTouches[z],n.wf=1,u[n.identifier]=n;for(z=0;z<m.targetTouches.length;++z)u[m.targetTouches[z].identifier].Df=1;x=h?D(1696):xe;B[x>>3]=m.timeStamp;var A=x>>2;v[A+3]=m.ctrlKey;v[A+4]=m.shiftKey;v[A+5]=m.altKey;v[A+6]=m.metaKey;A+=7;var K=Le(a),
M=0;for(z in u)if(n=u[z],v[A]=n.identifier,v[A+1]=n.screenX,v[A+2]=n.screenY,v[A+3]=n.clientX,v[A+4]=n.clientY,v[A+5]=n.pageX,v[A+6]=n.pageY,v[A+7]=n.wf,v[A+8]=n.Df,v[A+9]=n.clientX-K.left,v[A+10]=n.clientY-K.top,A+=13,31<++M)break;v[x+8>>2]=M;h?W(h,d,e,x,b):J(d)(e,x,b)&&m.preventDefault()},me:c})}function Qf(a,b,c,d,e){if(k)return I(53,1,a,b,c,d,e);Pf(a,b,c,d,25,"touchcancel",e);return 0}function Rf(a,b,c,d,e){if(k)return I(54,1,a,b,c,d,e);Pf(a,b,c,d,23,"touchend",e);return 0}
function Sf(a,b,c,d,e){if(k)return I(55,1,a,b,c,d,e);Pf(a,b,c,d,24,"touchmove",e);return 0}function Tf(a,b,c,d,e){if(k)return I(56,1,a,b,c,d,e);Pf(a,b,c,d,22,"touchstart",e);return 0}function Uf(a,b,c,d){var e=Be[1];d=le(d);ye||(ye=D(8));V({target:e,je:"visibilitychange",oe:c,qe:function(f){f=f||event;var h=d?D(8):ye,m=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);v[h>>2]=document.hidden;v[h+4>>2]=m;d?W(d,c,21,h,a):J(c)(21,h,a)&&f.preventDefault()},me:b})}
function Vf(a,b,c,d){if(k)return I(57,1,a,b,c,d);if(!Be[1])return-4;Uf(a,b,c,d);return 0}function Wf(a,b,c,d,e){e=le(e);ze||(ze=D(104));V({target:a,De:!0,je:"wheel",oe:d,qe:function(f){f=f||event;var h=e?D(104):ze;Ef(h,f,a);B[h+72>>3]=f.deltaX;B[h+80>>3]=f.deltaY;B[h+88>>3]=f.deltaZ;v[h+96>>2]=f.deltaMode;e?W(e,d,9,h,b):J(d)(9,h,b)&&f.preventDefault()},me:c})}function Xf(a,b,c,d,e){if(k)return I(58,1,a,b,c,d,e);a=X(a);return"undefined"!=typeof a.onwheel?(Wf(a,b,c,d,e),0):-1}
function Yf(a){if(k)return I(59,1,a);na(va(a))}var Zf={};function $f(){if(!ag){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Zf)void 0===Zf[b]?delete a[b]:a[b]=Zf[b];var c=[];for(b in a)c.push(b+"="+a[b]);ag=c}return ag}var ag;
function bg(a,b){if(k)return I(60,1,a,b);var c=0;$f().forEach(function(d,e){var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)t[e++>>0]=d.charCodeAt(f);t[e>>0]=0;c+=d.length+1});return 0}function cg(a,b){if(k)return I(61,1,a,b);var c=$f();w[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});w[b>>2]=d;return 0}
function dg(a){if(k)return I(62,1,a);try{var b=Xb(a);if(null===b.Ae)throw new F(8);b.cf&&(b.cf=null);try{b.fe.close&&b.fe.close(b)}catch(c){throw c;}finally{zb[b.Ae]=null}b.Ae=null;return 0}catch(c){if("undefined"==typeof Ub||!(c instanceof F))throw c;return c.Ee}}
function eg(a,b,c,d){if(k)return I(63,1,a,b,c,d);try{a:{var e=Xb(a);a=b;for(var f=b=0;f<c;f++){var h=w[a>>2],m=w[a+4>>2];a+=8;var n=e,u=h,x=m,z=void 0;if(0>x||0>z)throw new F(28);if(null===n.Ae)throw new F(8);if(1===(n.flags&2097155))throw new F(8);if(16384===(n.node.mode&61440))throw new F(31);if(!n.fe.read)throw new F(28);var A="undefined"!=typeof z;if(!A)z=n.position;else if(!n.seekable)throw new F(70);var K=n.fe.read(n,t,u,x,z);A||(n.position+=K);var M=K;if(0>M){var ia=-1;break a}b+=M;if(M<m)break}ia=
b}w[d>>2]=ia;return 0}catch(ja){if("undefined"==typeof Ub||!(ja instanceof F))throw ja;return ja.Ee}}
function fg(a,b,c,d,e){if(k)return I(64,1,a,b,c,d,e);try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var f=Xb(a);Rb(f,b,d);$a=[f.position>>>0,(C=f.position,1<=+Math.abs(C)?0<C?(Math.min(+Math.floor(C/4294967296),4294967295)|0)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];v[e>>2]=$a[0];v[e+4>>2]=$a[1];f.cf&&0===b&&0===d&&(f.cf=null);return 0}catch(h){if("undefined"==typeof Ub||!(h instanceof F))throw h;return h.Ee}}
function gg(a,b,c,d){if(k)return I(65,1,a,b,c,d);try{a:{var e=Xb(a);a=b;for(var f=b=0;f<c;f++){var h=w[a>>2],m=w[a+4>>2];a+=8;var n=e,u=h,x=m,z=void 0;if(0>x||0>z)throw new F(28);if(null===n.Ae)throw new F(8);if(0===(n.flags&2097155))throw new F(8);if(16384===(n.node.mode&61440))throw new F(31);if(!n.fe.write)throw new F(28);n.seekable&&n.flags&1024&&Rb(n,0,2);var A="undefined"!=typeof z;if(!A)z=n.position;else if(!n.seekable)throw new F(70);var K=n.fe.write(n,t,u,x,z,void 0);A||(n.position+=K);var M=
K;if(0>M){var ia=-1;break a}b+=M}ia=b}w[d>>2]=ia;return 0}catch(ja){if("undefined"==typeof Ub||!(ja instanceof F))throw ja;return ja.Ee}}function lg(a,b){lg.Ff||(lg.Ff=lb());for(var c=0;c<b;c++)t[a+c>>0]=lg.Ff();return 0}E.fg();function Hb(a,b,c,d){a||(a=this);this.parent=a;this.we=a.we;this.We=null;this.id=Ab++;this.name=b;this.mode=c;this.ee={};this.fe={};this.Ye=d}
Object.defineProperties(Hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});La();Bb=Array(4096);Ob(G,"/");H("/tmp",16895,0);H("/home",16895,0);H("/home/web_user",16895,0);
(()=>{H("/dev",16895,0);pb(259,{read:()=>0,write:(b,c,d,e)=>e});Pb("/dev/null",259);ob(1280,rb);ob(1536,sb);Pb("/dev/tty",1280);Pb("/dev/tty1",1536);var a=lb();Ma("random",a);Ma("urandom",a);H("/dev/shm",16895,0);H("/dev/shm/tmp",16895,0)})();(()=>{H("/proc",16895,0);var a=H("/proc/self",16895,0);H("/proc/self/fd",16895,0);Ob({we:()=>{var b=ub(a,"fd",16895,73);b.ee={Ie:(c,d)=>{var e=zb[+d];if(!e)throw new F(8);c={parent:null,we:{Af:"fake"},ee:{Je:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
g.requestFullscreen=function(a,b){cd(a,b)};g.requestAnimationFrame=function(a){Bc(a)};g.setCanvasSize=function(a,b,c){ed(g.canvas,a,b);c||fd()};g.pauseMainLoop=function(){xc=null;Ec++};g.resumeMainLoop=function(){Ec++;var a=tc,b=uc,c=vc;vc=null;Cc(c,0,!1,Dc,!0);sc(a,b);xc()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Wc(a,b,c,d)};for(var N,Z=0;32>Z;++Z)We.push(Array(Z));
var mg=new Float32Array(288);for(Z=0;288>Z;++Z)gf[Z]=mg.subarray(0,Z+1);var ng=new Int32Array(288);for(Z=0;288>Z;++Z)hf[Z]=ng.subarray(0,Z+1);
var og=[null,Yb,$b,lc,nc,pc,qc,pd,qd,Hd,Id,Jd,Od,Pd,Qd,Rd,Sd,Td,Vd,Wd,Xd,Yd,Zd,$d,Ne,De,Ge,Pe,Qe,Re,Te,Ue,Ve,mf,nf,of,qf,sf,tf,uf,wf,yf,zf,Bf,Cf,Df,Gf,Hf,If,Jf,Kf,Mf,Of,Qf,Rf,Sf,Tf,Vf,Xf,Yf,bg,cg,dg,eg,fg,gg],qg={Oa:function(a,b){J(a)(b)},Va:function(a){pg(a,!fa,1,!ea);E.Lf()},I:function(a){k?postMessage({cmd:"cleanupThread",thread:a}):fb(a)},Pa:mc,L:nc,ab:pc,bb:qc,fb:function(){},gb:function(){p("To use dlopen, you need enable dynamic linking, see https://github.com/emscripten-core/emscripten/wiki/Linking")},
eb:function(){return Date.now()},Qa:function(){return 2097152},db:function(){return!0},Sa:function(a,b,c,d){if(a==b)setTimeout(()=>dc(d));else if(k)postMessage({targetThread:a,cmd:"processProxyingQueue",queue:d});else{a=E.ye[a];if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:d})}return 1},Ua:function(){return-1},H:function(){p("")},Ka:pd,Rc:qd,vc:Hd,$b:Id,kc:Jd,Qb:Od,Gc:Pd,M:Qd,Ia:Rd,ld:Sd,Eb:Td,Ja:Vd,tb:Wd,ib:Xd,ad:Yd,Ra:Zd,$a:$d,Fb:function(a,b,c){b=be(b,c);return db[a].apply(null,
b)},b:function(a,b,c){b=be(b,c);return k?I.apply(null,[-1-a,1].concat(b)):db[a].apply(null,b)},Hd:function(){xc=null;Ec++;vc=null},J:function(){fa||Lc("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")},Ba:Ne,Ga:Pe,f:Qe,d:Re,za:Te,c:zc,Ea:Ue,Ha:Ve,fa:function(a){N.activeTexture(a)},ea:function(a,b){N.attachShader(Q[a],R[b])},va:function(a,b){N.pe.beginQueryEXT(a,S[b])},da:function(a,b,c){N.bindAttribLocation(Q[a],
b,va(c))},ca:function(a,b){N.bindBuffer(a,vd[b])},ba:function(a,b){N.bindFramebuffer(a,wd[b])},aa:function(a,b){N.bindRenderbuffer(a,xd[b])},$:function(a,b){N.bindTexture(a,yd[b])},na:function(a){N.bindVertexArray(zd[a])},_:function(a,b,c,d){N.blendColor(a,b,c,d)},Z:function(a){N.blendEquation(a)},Y:function(a,b){N.blendEquationSeparate(a,b)},X:function(a,b){N.blendFunc(a,b)},W:function(a,b,c,d){N.blendFuncSeparate(a,b,c,d)},V:function(a,b,c,d){N.bufferData(a,c?q.subarray(c,c+b):b,d)},U:function(a,
b,c,d){N.bufferSubData(a,b,q.subarray(d,d+c))},T:function(a){return N.checkFramebufferStatus(a)},S:function(a){N.clear(a)},R:function(a,b,c,d){N.clearColor(a,b,c,d)},Q:function(a){N.clearDepth(a)},P:function(a){N.clearStencil(a)},O:function(a,b,c,d){N.colorMask(!!a,!!b,!!c,!!d)},N:function(a){N.compileShader(R[a])},Fd:function(a,b,c,d,e,f,h,m){N.compressedTexImage2D(a,b,c,d,e,f,m?q.subarray(m,m+h):null)},Ed:function(a,b,c,d,e,f,h,m,n){N.compressedTexSubImage2D(a,b,c,d,e,f,h,n?q.subarray(n,n+m):null)},
Dd:function(a,b,c,d,e,f,h,m){N.copyTexImage2D(a,b,c,d,e,f,h,m)},Cd:function(a,b,c,d,e,f,h,m){N.copyTexSubImage2D(a,b,c,d,e,f,h,m)},Bd:function(){var a=Dd(Q),b=N.createProgram();b.name=a;b.Te=b.Re=b.Se=0;b.hf=1;Q[a]=b;return a},Ad:function(a){var b=Dd(R);R[b]=N.createShader(a);return b},zd:function(a){N.cullFace(a)},yd:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=vd[d];e&&(N.deleteBuffer(e),e.name=0,vd[d]=null)}},xd:function(a,b){for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=wd[d];e&&(N.deleteFramebuffer(e),
e.name=0,wd[d]=null)}},wd:function(a){if(a){var b=Q[a];b?(N.deleteProgram(b),b.name=0,Q[a]=null):T(1281)}},xa:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(N.pe.deleteQueryEXT(e),S[d]=null)}},vd:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=xd[d];e&&(N.deleteRenderbuffer(e),e.name=0,xd[d]=null)}},ud:function(a){if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T(1281)}},td:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=yd[d];e&&(N.deleteTexture(e),e.name=0,yd[d]=
null)}},ma:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];N.deleteVertexArray(zd[d]);zd[d]=null}},sd:function(a){N.depthFunc(a)},rd:function(a){N.depthMask(!!a)},qd:function(a,b){N.depthRange(a,b)},pd:function(a,b){N.detachShader(Q[a],R[b])},od:function(a){N.disable(a)},nd:function(a){N.disableVertexAttribArray(a)},md:function(a,b,c){N.drawArrays(a,b,c)},ia:function(a,b,c,d){N.drawArraysInstanced(a,b,c,d)},ja:function(a,b){for(var c=We[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];N.drawBuffers(c)},kd:function(a,
b,c,d){N.drawElements(a,b,c,d)},ha:function(a,b,c,d,e){N.drawElementsInstanced(a,b,c,d,e)},jd:function(a){N.enable(a)},id:function(a){N.enableVertexAttribArray(a)},ua:function(a){N.pe.endQueryEXT(a)},hd:function(){N.finish()},gd:function(){N.flush()},fd:function(a,b,c,d){N.framebufferRenderbuffer(a,b,c,xd[d])},ed:function(a,b,c,d,e){N.framebufferTexture2D(a,b,c,yd[d],e)},dd:function(a){N.frontFace(a)},cd:function(a,b){Xe(a,b,"createBuffer",vd)},$c:function(a,b){Xe(a,b,"createFramebuffer",wd)},ya:function(a,
b){for(var c=0;c<a;c++){var d=N.pe.createQueryEXT();if(!d){for(T(1282);c<a;)v[b+4*c++>>2]=0;break}var e=Dd(S);d.name=e;S[e]=d;v[b+4*c>>2]=e}},_c:function(a,b){Xe(a,b,"createRenderbuffer",xd)},Zc:function(a,b){Xe(a,b,"createTexture",yd)},la:function(a,b){Xe(a,b,"createVertexArray",zd)},bd:function(a){N.generateMipmap(a)},Yc:function(a,b,c,d,e,f,h){Ye("getActiveAttrib",a,b,c,d,e,f,h)},Xc:function(a,b,c,d,e,f,h){Ye("getActiveUniform",a,b,c,d,e,f,h)},Wc:function(a,b,c,d){a=N.getAttachedShaders(Q[a]);
var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=R.indexOf(a[b])},Vc:function(a,b){return N.getAttribLocation(Q[a],va(b))},Uc:function(a,b){$e(a,b,4)},Tc:function(a,b,c){c?v[c>>2]=N.getBufferParameter(a,b):T(1281)},Sc:function(){var a=N.getError()||Cd;Cd=0;return a},Qc:function(a,b){$e(a,b,2)},Pc:function(a,b,c,d){a=N.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},Oc:function(a,b){$e(a,b,0)},Mc:function(a,
b,c,d){a=N.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?r(a,d,b):0;c&&(v[c>>2]=b)},Nc:function(a,b,c){if(c)if(a>=ud)T(1281);else if(a=Q[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Te)for(b=0;b<N.getProgramParameter(a,35718);++b)a.Te=Math.max(a.Te,N.getActiveUniform(a,b).name.length+1);v[c>>2]=a.Te}else if(35722==b){if(!a.Re)for(b=0;b<N.getProgramParameter(a,35721);++b)a.Re=Math.max(a.Re,N.getActiveAttrib(a,b).name.length+
1);v[c>>2]=a.Re}else if(35381==b){if(!a.Se)for(b=0;b<N.getProgramParameter(a,35382);++b)a.Se=Math.max(a.Se,N.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Se}else v[c>>2]=N.getProgramParameter(a,b);else T(1281)},pa:function(a,b,c){if(c){a=N.pe.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Ze(c,d)}else T(1281)},ra:function(a,b,c){if(c){a=N.pe.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},oa:function(a,b,c){if(c){a=N.pe.getQueryObjectEXT(S[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;Ze(c,d)}else T(1281)},qa:function(a,b,c){if(c){a=N.pe.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},sa:function(a,b,c){c?v[c>>2]=N.pe.getQueryEXT(a,b):T(1281)},Lc:function(a,b,c){c?v[c>>2]=N.getRenderbufferParameter(a,b):T(1281)},Jc:function(a,b,c,d){a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?r(a,d,b):0;c&&(v[c>>2]=b)},Ic:function(a,b,c,d){a=N.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;
v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},Hc:function(a,b,c,d){if(a=N.getShaderSource(R[a]))b=0<b&&d?r(a,d,b):0,c&&(v[c>>2]=b)},Kc:function(a,b,c){c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=N.getShaderParameter(R[a],b):T(1281)},Fc:function(a){var b=Ad[a];if(!b){switch(a){case 7939:b=N.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=af(b.join(" "));break;
case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||T(1280);b=b&&af(b);break;case 7938:b=af("OpenGL ES 2.0 ("+N.getParameter(7938)+")");break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=af(b);break;default:T(1280)}Ad[a]=b}return b},Ec:function(a,b,c){c?y[c>>2]=N.getTexParameter(a,b):T(1281)},Dc:function(a,b,c){c?v[c>>2]=N.getTexParameter(a,b):T(1281)},
Ac:function(a,b){b=va(b);if(a=Q[a]){cf(a);var c=a.Ne,d=0,e=b,f=bf(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Of[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T(1281);return-1},Cc:function(a,b,c){df(a,b,c,2)},Bc:function(a,b,c){df(a,b,c,0)},xc:function(a,b,c){c?v[c>>2]=N.getVertexAttribOffset(a,b):T(1281)},zc:function(a,b,c){ef(a,b,c,2)},yc:function(a,b,c){ef(a,b,c,5)},wc:function(a,b){N.hint(a,b)},uc:function(a){return(a=vd[a])?N.isBuffer(a):0},tc:function(a){return N.isEnabled(a)},
sc:function(a){return(a=wd[a])?N.isFramebuffer(a):0},rc:function(a){return(a=Q[a])?N.isProgram(a):0},wa:function(a){return(a=S[a])?N.pe.isQueryEXT(a):0},qc:function(a){return(a=xd[a])?N.isRenderbuffer(a):0},pc:function(a){return(a=R[a])?N.isShader(a):0},oc:function(a){return(a=yd[a])?N.isTexture(a):0},ka:function(a){return(a=zd[a])?N.isVertexArray(a):0},nc:function(a){N.lineWidth(a)},mc:function(a){a=Q[a];N.linkProgram(a);a.Ne=0;a.Of={}},lc:function(a,b){3317==a&&(Bd=b);N.pixelStorei(a,b)},jc:function(a,
b){N.polygonOffset(a,b)},ta:function(a,b){N.pe.queryCounterEXT(S[a],b)},ic:function(a,b,c,d,e,f,h){(h=ff(f,e,c,d,h))?N.readPixels(a,b,c,d,e,f,h):T(1280)},hc:function(){},gc:function(a,b,c,d){N.renderbufferStorage(a,b,c,d)},fc:function(a,b){N.sampleCoverage(a,!!b)},ec:function(a,b,c,d){N.scissor(a,b,c,d)},dc:function(){T(1280)},cc:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?v[d+4*f>>2]:-1;e+=va(v[c+4*f>>2],0>h?void 0:h)}N.shaderSource(R[a],e)},bc:function(a,b,c){N.stencilFunc(a,b,c)},ac:function(a,
b,c,d){N.stencilFuncSeparate(a,b,c,d)},_b:function(a){N.stencilMask(a)},Zb:function(a,b){N.stencilMaskSeparate(a,b)},Yb:function(a,b,c){N.stencilOp(a,b,c)},Xb:function(a,b,c,d){N.stencilOpSeparate(a,b,c,d)},Wb:function(a,b,c,d,e,f,h,m,n){N.texImage2D(a,b,c,d,e,f,h,m,n?ff(m,h,d,e,n):null)},Vb:function(a,b,c){N.texParameterf(a,b,c)},Ub:function(a,b,c){N.texParameterf(a,b,y[c>>2])},Tb:function(a,b,c){N.texParameteri(a,b,c)},Sb:function(a,b,c){N.texParameteri(a,b,v[c>>2])},Rb:function(a,b,c,d,e,f,h,m,
n){var u=null;n&&(u=ff(m,h,e,f,n));N.texSubImage2D(a,b,c,d,e,f,h,m,u)},Pb:function(a,b){N.uniform1f(Y(a),b)},Ob:function(a,b,c){if(288>=b)for(var d=gf[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);N.uniform1fv(Y(a),d)},Nb:function(a,b){N.uniform1i(Y(a),b)},Mb:function(a,b,c){if(288>=b)for(var d=hf[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);N.uniform1iv(Y(a),d)},Lb:function(a,b,c){N.uniform2f(Y(a),b,c)},Kb:function(a,b,c){if(144>=b)for(var d=gf[2*b-1],e=
0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);N.uniform2fv(Y(a),d)},Jb:function(a,b,c){N.uniform2i(Y(a),b,c)},Ib:function(a,b,c){if(144>=b)for(var d=hf[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);N.uniform2iv(Y(a),d)},Hb:function(a,b,c,d){N.uniform3f(Y(a),b,c,d)},Gb:function(a,b,c){if(96>=b)for(var d=gf[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>
2,c+12*b>>2);N.uniform3fv(Y(a),d)},Db:function(a,b,c,d){N.uniform3i(Y(a),b,c,d)},Cb:function(a,b,c){if(96>=b)for(var d=hf[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);N.uniform3iv(Y(a),d)},Bb:function(a,b,c,d,e){N.uniform4f(Y(a),b,c,d,e)},Ab:function(a,b,c){if(72>=b){var d=gf[4*b-1];c>>=2;for(var e=0;e<4*b;e+=4){var f=c+e;d[e]=y[f];d[e+1]=y[f+1];d[e+2]=y[f+2];d[e+3]=y[f+3]}}else d=y.subarray(c>>2,c+16*b>>2);N.uniform4fv(Y(a),
d)},zb:function(a,b,c,d,e){N.uniform4i(Y(a),b,c,d,e)},yb:function(a,b,c){if(72>=b)for(var d=hf[4*b-1],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);N.uniform4iv(Y(a),d)},xb:function(a,b,c,d){if(72>=b)for(var e=gf[4*b-1],f=0;f<4*b;f+=4)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);N.uniformMatrix2fv(Y(a),!!c,e)},wb:function(a,b,c,d){if(32>=
b)for(var e=gf[9*b-1],f=0;f<9*b;f+=9)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2];else e=y.subarray(d>>2,d+36*b>>2);N.uniformMatrix3fv(Y(a),!!c,e)},vb:function(a,b,c,d){if(18>=b){var e=gf[16*b-1];d>>=2;for(var f=0;f<16*b;f+=16){var h=d+f;e[f]=y[h];e[f+1]=y[h+1];e[f+2]=y[h+2];e[f+3]=y[h+3];e[f+4]=y[h+4];e[f+5]=y[h+5];e[f+6]=y[h+6];e[f+7]=
y[h+7];e[f+8]=y[h+8];e[f+9]=y[h+9];e[f+10]=y[h+10];e[f+11]=y[h+11];e[f+12]=y[h+12];e[f+13]=y[h+13];e[f+14]=y[h+14];e[f+15]=y[h+15]}}else e=y.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(Y(a),!!c,e)},ub:function(a){a=Q[a];N.useProgram(a);N.Sf=a},sb:function(a){N.validateProgram(Q[a])},rb:function(a,b){N.vertexAttrib1f(a,b)},qb:function(a,b){N.vertexAttrib1f(a,y[b>>2])},pb:function(a,b,c){N.vertexAttrib2f(a,b,c)},ob:function(a,b){N.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},nb:function(a,b,c,d){N.vertexAttrib3f(a,
b,c,d)},mb:function(a,b){N.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},lb:function(a,b,c,d,e){N.vertexAttrib4f(a,b,c,d,e)},kb:function(a,b){N.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},ga:function(a,b){N.vertexAttribDivisor(a,b)},jb:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},hb:function(a,b,c,d){N.viewport(a,b,c,d)},i:function(){return 0},Ya:function(a,b,c){q.copyWithin(a,b,b+c)},Ta:function(a,b,c){kf.length=b;c>>=3;for(var d=0;d<b;d++)kf[d]=B[c+d];return(0>a?db[-a-
1]:og[a]).apply(null,kf)},Ca:mf,G:nf,Na:function(){p("OOM")},Aa:function(){return noExitRuntime},Fa:of,m:qf,y:sf,e:He,j:tf,z:uf,p:wf,h:yf,g:zf,s:Bf,q:Cf,r:Df,Gd:function(a,b,c){a=J(a);Cc(a,b,c)},E:Gf,C:Hf,B:If,F:Jf,D:Kf,t:Mf,o:Of,u:Qf,w:Rf,v:Sf,x:Tf,n:Vf,A:Xf,Da:Yf,k:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},cb:function(){throw"unwind";},Wa:bg,Xa:cg,l:Zb,K:dg,_a:eg,La:fg,Za:gg,Ma:lg,a:qa};
(function(){function a(e,f){g.asm=e.exports;E.Mf.push(g.asm.Pd);Da=g.asm.Kd;Fa.unshift(g.asm.Id);ra=f;if(!k){var h=E.ze.length;E.ze.forEach(function(m){E.xf(m,function(){if(!--h&&(Sa--,g.monitorRunDependencies&&g.monitorRunDependencies(Sa),0==Sa&&(null!==Ta&&(clearInterval(Ta),Ta=null),Ua))){var n=Ua;Ua=null;n()}})})}}function b(e){a(e.instance,e.module)}function c(e){return Za().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){l("failed to asynchronously prepare wasm: "+
f);p(f)})}var d={a:qg};k||(Sa++,g.monitorRunDependencies&&g.monitorRunDependencies(Sa));if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return pa||"function"!=typeof WebAssembly.instantiateStreaming||Wa()||"function"!=typeof fetch?c(b):fetch(Xa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){l("wasm streaming compile failed: "+f);l("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.Id).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Jd).apply(null,arguments)};
var Nd=g._free=function(){return(Nd=g._free=g.asm.Ld).apply(null,arguments)},D=g._malloc=function(){return(D=g._malloc=g.asm.Md).apply(null,arguments)},cc=g._pthread_self=function(){return(cc=g._pthread_self=g.asm.Nd).apply(null,arguments)},oc=g.___errno_location=function(){return(oc=g.___errno_location=g.asm.Od).apply(null,arguments)};g.__emscripten_tls_init=function(){return(g.__emscripten_tls_init=g.asm.Pd).apply(null,arguments)};
g.__emscripten_proxy_main=function(){return(g.__emscripten_proxy_main=g.asm.Qd).apply(null,arguments)};var pg=g.__emscripten_thread_init=function(){return(pg=g.__emscripten_thread_init=g.asm.Rd).apply(null,arguments)};g.__emscripten_thread_crashed=function(){return(g.__emscripten_thread_crashed=g.asm.Sd).apply(null,arguments)};
var jf=g._emscripten_run_in_main_runtime_thread_js=function(){return(jf=g._emscripten_run_in_main_runtime_thread_js=g.asm.Td).apply(null,arguments)},ke=g._emscripten_dispatch_to_thread_=function(){return(ke=g._emscripten_dispatch_to_thread_=g.asm.Ud).apply(null,arguments)},rc=g.__emscripten_proxy_execute_task_queue=function(){return(rc=g.__emscripten_proxy_execute_task_queue=g.asm.Vd).apply(null,arguments)},bc=g.__emscripten_thread_free_data=function(){return(bc=g.__emscripten_thread_free_data=g.asm.Wd).apply(null,
arguments)},kc=g.__emscripten_thread_exit=function(){return(kc=g.__emscripten_thread_exit=g.asm.Xd).apply(null,arguments)},Va=g.___trap=function(){return(Va=g.___trap=g.asm.Yd).apply(null,arguments)},jc=g._emscripten_stack_set_limits=function(){return(jc=g._emscripten_stack_set_limits=g.asm.Zd).apply(null,arguments)},gc=g.stackSave=function(){return(gc=g.stackSave=g.asm._d).apply(null,arguments)},hc=g.stackRestore=function(){return(hc=g.stackRestore=g.asm.$d).apply(null,arguments)},je=g.stackAlloc=
function(){return(je=g.stackAlloc=g.asm.ae).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.be).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.ce).apply(null,arguments)};g.keepRuntimeAlive=function(){return noExitRuntime};g.wasmMemory=qa;g.ExitStatus=eb;var rg;Ua=function sg(){rg||tg();rg||(Ua=sg)};
function ug(a){var b=g.__emscripten_proxy_main;a=a||[];a.unshift(ca);var c=a.length,d=je(4*(c+1)),e=d>>2;a.forEach(f=>{var h=e++,m=xa(f)+1,n=je(m);wa(f,t,n,m);v[h]=n});v[e]=0;b(c,d)}
function tg(){function a(){if(!rg&&(rg=!0,g.calledRun=!0,!sa)){Ja();k||Qa(Ga);if(g.onRuntimeInitialized)g.onRuntimeInitialized();vg&&ug(b);if(!k){if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Ia.unshift(c)}Qa(Ia)}}}var b=b||ba;if(!(0<Sa))if(k)Ja(),postMessage({cmd:"loaded"});else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ra();Qa(Ea);0<Sa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},
1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var vg=!0;g.noInitialRun&&(vg=!1);tg();
